"""Generates vectors/mizo.json -- the conformance vectors described in
docs/architecture.md: a checked-in table for the full supported range,
generated from the reference engine (the oracle), that every target package
will eventually be tested against.

Run from inside reference/ (same convention as pytest, see README.md):

    python generate_vectors.py

Regenerate and commit vectors/mizo.json whenever languages/mizo.yaml's
lexicon or grammar changes -- it's a snapshot, not computed at test time, so
test_engine.py can catch a spec edit that silently changed output and wasn't
followed by a regenerate.

Each entry has three fields:

    { "number": "58",
      "text": "sawm nga pariat",
      "accepted_inputs": [ ... ] }

`text` is the canonical output: what number_to_text() must produce.
`accepted_inputs` is what text_to_number() must accept, and it includes
`text` itself, so a target can iterate one field rather than remembering to
also test the canonical form. See below for how the list is chosen.

Why `number` is a string (#12)
------------------------------
Every number in this file today is between 0 and 100, so JSON's number type
would do. It is written as a string anyway, because the format outlives the
range. #27 sets Mizo's eventual ceiling at 10^18 - 1, which is 111x larger
than JavaScript's Number.MAX_SAFE_INTEGER: a standard JSON.parse reads
999999999999999999 back as 1000000000000000000. A JS target would then load
the vectors, compare its output against a silently wrong expected value, and
pass -- a conformance suite that certifies a broken implementation is worse
than no suite at all. Python's arbitrary-precision ints hide this, so it
would go unnoticed until the npm target exists, by which point the format is
fixed and every vectors file needs regenerating. Deciding it now costs one
str() here and an int() in the tests.
"""

import itertools
import json
import re
from pathlib import Path

# These are engine internals, imported deliberately rather than reimplemented.
# The vectors are only meaningful if they are generated by the same rule
# selection, rendering and leniency the engine itself uses -- a local copy
# would drift, and the drift would show up as vectors that certify behaviour
# the oracle doesn't have. compile_spec.py reaches into engine.py for the
# same reason.
from engine import (
    _PLACEHOLDER_RE,
    _find_rule,
    _positional_variables,
    _render,
    _strip_diacritics,
    load,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT / "languages" / "mizo.yaml"
VECTORS_PATH = REPO_ROOT / "vectors" / "mizo.json"


def numbers_to_cover(spec) -> list:
    """Which numbers get an entry in the vectors file.

    Today: every number in the supported range, which is 0-100. #19 extends
    that to 100-199 and it stays exhaustive. The policy agreed in #12 for
    when it stops being exhaustive:

    - Enumerate every number while the range is under roughly 1,000 entries.
      The threshold is arbitrary -- writing it down is the point, so that
      growing past it is a decision rather than a surprise.
    - Above that, sample one entry per structural case rather than one per
      number, using the list in #27: each scale boundary and the numbers
      either side of it, the x1 cases, the 10^2/10^3 behavioural split,
      numbers with zero digits in the middle, and supports.max itself.

    This exists as a named function so #19 and whatever follows it edit one
    function instead of restructuring the generator. Which numbers get an
    entry and which spellings each entry accepts are independent decisions:
    sampling picks the rows, accepted_inputs() fills them in, and the rule
    it uses is per-entry so it already works at any range.
    """
    return list(range(spec.supports["min"], spec.supports["max"] + 1))


def accepted_inputs(spec, n: int, exhaustive: bool = False) -> list:
    """The spellings of `n` that text_to_number() must accept.

    These are *representative* accepted spellings, one per applicable parse
    feature -- not every accepted spelling. Don't document them as if they
    were exhaustive; the two assumptions that make a representative list
    sufficient, and the point where each stops holding, are at the bottom of
    this docstring.

    The bounded rule, per entry:

    - the canonical output;
    - one variant per applicable respelling feature, applied to the
      canonical output: case, diacritics, alternate word separator, and the
      connector in the last gap when the digit there adds to the scale word
      rather than multiplying it (see _connector_reads_as_and);
    - one combined variant with every applicable respelling applied at once,
      when more than one applies;
    - one plain variant per alternate template: each of the rule's
      parse_aliases, and, for a freestanding single digit, the other unit
      forms parse.accepted_forms allows.

    Not the cross product. One representative per feature is what makes a
    failure diagnostic: when a target fails an entry, the variant that failed
    names the feature that is broken. A cross product would report the same
    bug several dozen times and cost 18x the bytes for it.

    Connector placement is the last gap only, per #10 and the #12 decision,
    and only where that gap is a place "leh" can idiomatically go. The engine
    drops "leh" in any gap by deliberate design, but that is engine
    tolerance, not a target contract: listing every-gap forms would promote
    the tolerance into a requirement every future target must implement, for
    a string a Mizo speaker reads as "10 and 5 and 8" rather than as 58.
    Whatever #19 decides about where number_to_text() emits "leh" has to stay
    consistent with this, since the canonical output must always appear in
    accepted_inputs.

    Two assumptions hold this up, and both are load-bearing.

    First, that parse features compose, so covering each one separately
    covers them together. The engine's parse side is a pipeline -- normalise,
    split, drop connectors, resolve aliases, then match -- and each feature
    is one stage, so the assumption holds for the reference implementation
    and for #20's Python target, which is compiled from the same spec. It is
    not free, though: a target that reimplements parsing some other way could
    pass every entry here and still fail on a combination. The exhaustive
    sweep that would catch that lives in test_engine.py, and a target cannot
    import it -- reference/ is not shipped. Pass exhaustive=True to generate
    the full cross product.

    Second, that an entry's accepted spellings can be enumerated at all.
    That is true of every parse feature in the spec today, and it stops being
    true above 10^5: Mizo scale words multiply each other productively there
    (nuai za hnih for 10^5 x 200), and any scale may take any
    scale-multiplied expression as its multiplier, so the accepted spellings
    of one number stop being a list and become a grammar. Nothing to do about
    it at 0-100, but whoever extends the range past that boundary will need
    generation from parse features to become generation from a grammar. See
    #27 for the data and #12 for the discussion.
    """
    variables = _positional_variables(n)
    rule = _find_rule(spec.rules, n, variables)
    separators = spec.parse_config.get("word_separators", [" "])

    canonical_words = _split_words(_render(rule["output"], spec.lexicon, variables), separators)
    features = _applicable_respellings(spec, canonical_words, _connector_reads_as_and(rule))

    variants = set()
    if exhaustive:
        # Every template crossed with every subset of respellings, and with
        # the connector in every subset of gaps rather than only the last.
        # This is not a claim about which strings are Mizo -- it is a check
        # that the engine's tolerances genuinely compose.
        for words in _all_renderings(spec, rule, variables, separators):
            available = _connector_gaps(spec, words, ("connector",), every_gap=True)
            # The connector is varied by gap below, so it is not also varied
            # as a feature -- that would generate every string twice.
            respellings = [f for f in _applicable_respellings(spec, words) if f != "connector"]
            for subset in _subsets(respellings):
                for gaps in _subsets(available):
                    variants.add(_respell(words, spec, subset, gaps))
    else:
        variants.add(_respell(canonical_words, spec, (), ()))
        for feature in features:
            gaps = _connector_gaps(spec, canonical_words, (feature,))
            variants.add(_respell(canonical_words, spec, (feature,), gaps))
        if len(features) > 1:
            gaps = _connector_gaps(spec, canonical_words, features)
            variants.add(_respell(canonical_words, spec, features, gaps))
        for template in _alternate_templates(spec, rule):
            words = _split_words(_render(template, spec.lexicon, variables), separators)
            variants.add(_respell(words, spec, (), ()))

    return sorted(variants)


def _alternate_templates(spec, rule) -> list:
    """Templates for `n` other than its canonical output.

    Two sources. `parse_aliases` are declared per rule -- extra templates
    accepted when parsing and never produced by number_to_text(), e.g.
    compound_tens' shorthand that drops the scale word. The other is the
    engine's leniency for a phrase that is a single freestanding
    placeholder, which accepts any unit form parse.accepted_forms allows
    ("khat" as well as "pakhat" for 1). That one is expressed here as a
    synthetic template with the field name swapped, so both sources go
    through the same render path.

    Which fields leniency allows comes from the engine rather than from a
    "standalone"/"bound" list written out here, so this keeps working when
    #31 moves that decision into the spec.
    """
    templates = list(rule.get("parse_aliases", []))

    placeholders = _PLACEHOLDER_RE.findall(rule["output"])
    if len(placeholders) == 1:
        table, raw_key, field = placeholders[0]
        for other in spec._acceptable_fields(table, field, lenient=True):
            if other != field:
                templates.append("{%s[%s].%s}" % (table, raw_key, other))
    return templates


def _applicable_respellings(spec, words, connector_allowed: bool = True) -> tuple:
    """Which respelling features actually produce something for this phrase.

    Applicability is checked rather than left to deduplication, because a
    feature that cannot apply must not be counted as covered: "sawm hnih"
    has no diacritics to strip, and a single-word phrase has no gap to put a
    connector or an alternate separator in. The same reasoning is why
    connector_allowed is threaded through here rather than only suppressing
    the gap: if the feature still counted as applicable, the combined
    variant would quietly lose its connector and the file would claim
    coverage it doesn't have.
    """
    parse = spec.parse_config
    features = []
    if parse.get("case_insensitive", False):
        features.append("case")
    if parse.get("strip_diacritics", False) and any(w != _strip_diacritics(w) for w in words):
        features.append("diacritics")
    if len(parse.get("word_separators", [" "])) > 1 and len(words) > 1:
        features.append("separator")
    if parse.get("connectors") and len(words) > 1 and connector_allowed:
        features.append("connector")
    return tuple(features)


# The positional variable for the least significant digit, per
# engine._positional_variables().
_LEAST_SIGNIFICANT_POSITION = "ones_digit"


def _connector_reads_as_and(rule) -> bool:
    """Whether this rule's last gap is somewhere a connector belongs.

    Last-gap-only (#12) is well defined mechanically, but the last gap isn't
    always the same kind of place. In teens and compound_tens the final digit
    is *added* to the scale word (11 = 10 + 1), so "sâwm leh pakhat" reads
    the way "leh" means. In exact_tens the final digit *multiplies* it
    (20 = 10 x 2), and the last gap is the only gap -- so the same rule would
    certify "sawm leh hnih" for 20, which a native speaker reads as "ten and
    two", i.e. as 12. That is the same objection that made connector
    placement last-gap-only in the first place, applied to a case that hadn't
    come up: the engine tolerates the string, but we shouldn't bless it.

    Detected positionally -- the final placeholder addresses the least
    significant digit -- rather than by checking for the field name "bound".
    Both split today's rules identically, but field names are Mizo's, and
    hardcoding those in language-agnostic code is exactly what #31 is about;
    positional variables are the engine's own vocabulary, which
    compile_spec.py already builds on.

    This is still a proxy with a known expiry. #27 notes that positional
    variables don't generalise past two digits, and #19 has to decide "leh"
    placement for multi-scale numbers anyway; whoever does that revisits
    this.
    """
    placeholders = _PLACEHOLDER_RE.findall(rule["output"])
    if len(placeholders) < 2:
        return False
    _table, raw_key, _field = placeholders[-1]
    return raw_key == _LEAST_SIGNIFICANT_POSITION


def _respell(words, spec, features, connector_gaps) -> str:
    """Write one phrase a different way, without changing which number it is.

    Order matters: the connector goes in before normalisation, so that it
    gets the same casing as the rest of the phrase rather than staying
    lowercase in an otherwise uppercase string.
    """
    parse = spec.parse_config
    separators = parse.get("word_separators", [" "])

    out = []
    for i, word in enumerate(words):
        out.append(word)
        if i in connector_gaps:
            out.append(parse["connectors"][0])
    if "diacritics" in features:
        out = [_strip_diacritics(w) for w in out]
    if "case" in features:
        out = [w.upper() for w in out]

    joiner = separators[1] if "separator" in features else separators[0]
    return joiner.join(out)


def _connector_gaps(spec, words, features, every_gap: bool = False) -> tuple:
    """Which gaps between words the connector may be inserted into.

    The last gap only, unless every_gap -- see accepted_inputs() for why the
    certified set is narrower than what the engine tolerates.
    """
    if "connector" not in features or not spec.parse_config.get("connectors") or len(words) < 2:
        return ()
    if every_gap:
        return tuple(range(len(words) - 1))
    return (len(words) - 2,)


def _all_renderings(spec, rule, variables, separators) -> list:
    templates = [rule["output"], *_alternate_templates(spec, rule)]
    return [_split_words(_render(t, spec.lexicon, variables), separators) for t in templates]


def _subsets(items) -> list:
    items = tuple(items)
    return [
        combo
        for size in range(len(items) + 1)
        for combo in itertools.combinations(items, size)
    ]


def _split_words(text: str, separators) -> list:
    pattern = "|".join(re.escape(sep) for sep in separators)
    return [word for word in re.split(pattern, text) if word]


def build_vectors(spec) -> list:
    """Build the vector table, checking every string it writes.

    Each accepted input is parsed back before it is written. A vector that
    doesn't parse is worse than a missing one -- it would be checked into
    git and every target would then be required to accept a string the
    oracle itself rejects -- so this fails loudly at generation time rather
    than shipping it.
    """
    vectors = []
    for n in numbers_to_cover(spec):
        text = spec.number_to_text(n)
        inputs = accepted_inputs(spec, n)
        for candidate in inputs:
            parsed = spec.text_to_number(candidate)
            if parsed != n:
                raise AssertionError(
                    f"generated accepted input {candidate!r} for n={n} parses back as {parsed}"
                )
        # Entries stay in numeric order; only accepted_inputs is sorted, so
        # that the file is byte-stable for the CI drift check. Sorting the
        # entries themselves would order them as strings ("10" before "2").
        vectors.append({"number": str(n), "text": text, "accepted_inputs": inputs})
    return vectors


def main() -> None:
    spec = load(SPEC_PATH)
    vectors = build_vectors(spec)
    VECTORS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(VECTORS_PATH, "w", encoding="utf-8") as f:
        json.dump(vectors, f, ensure_ascii=False, indent=2)
        f.write("\n")
    total = sum(len(v["accepted_inputs"]) for v in vectors)
    print(
        f"Wrote {len(vectors)} vectors ({total} accepted inputs) to "
        f"{VECTORS_PATH.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
