"""Generates vectors/mizo.json -- the conformance vectors described in
docs/architecture.md: a checked-in table for the full supported range,
generated from the reference engine (the oracle), that every target package
will eventually be tested against.

Run from inside reference/ (same convention as pytest, see README.md):

    python generate_vectors.py

Regenerate and commit vectors/mizo.json whenever languages/mizo.yaml's
lexicon or grammar changes -- it's a snapshot, not computed at test time, so
test_engine.py can catch a spec edit that silently changed output and wasn't
followed by a regenerate.

Each entry has three fields:

    { "number": "58",
      "text": "sawm nga pariat",
      "accepted_inputs": [ ... ] }

`text` is the canonical output: what number_to_text() must produce.
`accepted_inputs` is what text_to_number() must accept, and it includes
`text` itself, so a target can iterate one field rather than remembering to
also test the canonical form. See below for how the list is chosen.

Why `number` is a string (#12)
------------------------------
Every number in this file today is between 0 and 999, and Mizo's ceiling is
10^10 - 1 (#27, revised 2026-09-25), which JavaScript's
Number.MAX_SAFE_INTEGER holds exactly -- so JSON's number type would do. It
is written as a string anyway, because the format outlives the ceiling. The
decision was taken when the ceiling was 10^18 - 1, 111x past
MAX_SAFE_INTEGER, where a standard JSON.parse reads 999999999999999999 back
as 1000000000000000000. A JS target would then load the vectors, compare its
output against a silently wrong expected value, and pass -- a conformance
suite that certifies a broken implementation is worse than no suite at all.
#27 records that this comes back the moment the ceiling is raised past
2^53 - 1, and Python's arbitrary-precision ints would hide it until the npm
target exists. Keeping the string costs one str() here and an int() in the
tests; dropping it would mean regenerating every vectors file then.
"""

import itertools
import json
import re
from pathlib import Path

# These are engine internals, imported deliberately rather than reimplemented.
# The vectors are only meaningful if they are generated by the same rule
# selection, rendering and leniency the engine itself uses -- a local copy
# would drift, and the drift would show up as vectors that certify behaviour
# the oracle doesn't have. Rule selection and rendering are Spec methods now
# (Spec._find_rule, Spec._render_rule, Spec._with_connector), so the import
# shrank to the text helpers; the methods are private for the same reason
# these are, and the same rule applies if the surface grows further.
from engine import (
    _joinable_separators,
    _separator_pattern,
    _strip_diacritics,
    load,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT / "languages" / "mizo.yaml"
VECTORS_PATH = REPO_ROOT / "vectors" / "mizo.json"


# #12's threshold, applied as a value: every number below it gets an entry,
# whatever the range. #12 put it at "roughly 1,000 entries", which 0-999 is.
# Keeping all of 0-999 once the range grows past it is deliberate. The
# irregular Mizo lives there -- bare sâwm and zâ, the "hnih thum" shorthand,
# where "leh" goes -- and those 1,000 entries are the table step 4 of #27
# reproduced byte-identically: "the rules are scaffolding but the vectors are
# not -- they are facts about Mizo" (zoramt on #27, 2026-09-03).
EXHAUSTIVE_BELOW = 1000


def numbers_to_cover(spec, exhaustive_below: int = EXHAUSTIVE_BELOW) -> list:
    """Which numbers get an entry in the vectors file -- and which numbers
    every test that used to walk the whole supported range visits instead.

    The policy agreed in #12, decided with #65:

    - Every number below `exhaustive_below` (EXHAUSTIVE_BELOW, 1,000).
    - Above it, one number of each shape the grammar can render (see
      _shape_representatives), which is what the composition sweep and the
      round trips need, plus #27's structural cases (see _structural_cases),
      which are what a person reading the table looks for.
    - supports.min and supports.max, always.

    Below the threshold this is the whole range, so for a range that ends
    there -- Mizo's 0-999 today -- it is exactly what it used to be. Nothing
    is random: the same spec always gives the same list, which is what lets
    CI check that the vectors regenerate identically.

    `exhaustive_below` is a parameter so that the tests can sample a range
    that is still small enough to walk, and compare. That is the only
    evidence a sample is representative (see
    test_the_sample_loses_no_shape).

    Which numbers get an entry and which spellings each entry accepts are
    independent decisions: this picks the rows, accepted_inputs() fills them
    in, and its rule is per-entry so it works at any range.
    """
    low, high = spec.supports["min"], spec.supports["max"]
    numbers = set(range(low, min(high, exhaustive_below - 1) + 1))
    if high >= exhaustive_below:
        numbers |= set(_shape_representatives(spec, exhaustive_below).values())
        numbers |= _structural_cases(spec, exhaustive_below)
        numbers |= {low, high}
    return sorted(numbers)


def _shape(spec, n: int) -> tuple:
    """The shape of n's rendering, as numbers_to_sweep defines it: the rule
    that renders n; per template, its word count and whether any word
    carries a diacritic; and how many of the templates render to distinct
    strings. numbers_to_sweep's docstring says why each term is there."""
    separators = _joinable_separators(spec.parse_config)
    pattern = _separator_pattern(spec.parse_config)
    renderings = _all_renderings(spec, n, pattern, separators)
    per_template = tuple(
        (len(words), any(w != _strip_diacritics(w) for w in words))
        for words, _joiner in renderings
    )
    distinct = len({joiner.join(words) for words, joiner in renderings})
    return spec._find_rule(n)["name"], per_template, distinct


def _shape_representatives(spec, exhaustive_below: int) -> dict:
    """One number of each shape in the supported range, keyed by shape --
    found without walking the range.

    Rules recurse through {remainder}, so a number is its own rule's words
    followed by its remainder's rendering, and its shape is fixed by its
    rule, its multiplier and the *shape* of its remainder, not by which
    number the remainder is. Every shape at a scale is therefore some
    multiplier times the scale plus a representative of a shape below it.
    The exhaustive part seeds the table, and each scale above it adds
    multiplier x scale + r for every multiplier and every representative r
    found so far, keeping the first number of each new shape.

    That is an assumption about the grammar, not a fact about it -- a
    condition that tested a remainder's value rather than whether it is
    zero could break it -- so it is checked, not trusted:
    test_the_sample_loses_no_shape compares this against a walk of every
    number, over the part of the range that can still be walked.
    """
    low, high = spec.supports["min"], spec.supports["max"]
    representatives = {}
    for n in range(low, min(high, exhaustive_below - 1) + 1):
        representatives.setdefault(_shape(spec, n), n)
    scales = sorted(spec._emitting_scales)
    for i, scale in enumerate(scales):
        if scale > high:
            break
        above = scales[i + 1] if i + 1 < len(scales) else None
        if above is not None and above <= exhaustive_below:
            continue    # every number this scale renders is exhaustive
        # The multipliers this scale renders: up to the next scale, or for
        # the largest one, up to supports.max.
        top = (high // scale) if above is None else (above // scale - 1)
        remainders = sorted({0} | {r for r in representatives.values() if r < scale})
        for multiplier in range(1, top + 1):
            for remainder in remainders:
                n = multiplier * scale + remainder
                if low <= n <= high:
                    representatives.setdefault(_shape(spec, n), n)
    return representatives


def _structural_cases(spec, exhaustive_below: int) -> set:
    """#27's list of the cases a sampled table must still show, at each
    scale from `exhaustive_below` up:

    - the scale itself -- its x1 case -- and the numbers either side of it,
      which is also where the behaviour changes from one scale to the next;
    - every multiplier the scale takes, so every digit's form appears
      next to every scale word;
    - one digit below the scale with zeros around it (1001, 1010, 1100);
    - every place below the scale filled but one (1099, 1909, 1990) --
      #27's own hard case for where the connector goes.

    Mostly these are shapes _shape_representatives has already found. They
    are listed anyway because they are what a reader of the table looks for,
    and a sample chosen by shape alone could pick any number of a shape.
    """
    low, high = spec.supports["min"], spec.supports["max"]
    scales = sorted(spec._emitting_scales)
    cases = set()
    for i, scale in enumerate(scales):
        if scale < exhaustive_below:
            continue
        above = scales[i + 1] if i + 1 < len(scales) else high + 1
        cases |= {scale - 1, scale, scale + 1}
        cases |= {m * scale for m in range(1, above // scale)}
        full = scale - 1    # every place below the scale filled
        for j, place in enumerate(scales[:i]):
            digit = full % scales[j + 1] // place
            cases.add(scale + place)
            cases.add(scale + full - digit * place)
    return {n for n in cases if low <= n <= high}


def numbers_to_sweep(spec) -> list:
    """Which numbers the composition sweep visits, as against every number.

    The sweep asks whether the engine's parse tolerances compose. That is a
    question about the *shape* of a rendering -- how many words, whether any
    carries a diacritic, how many distinct spellings the rule's templates
    produce -- and not about which lexemes fill it. Two numbers of the same
    shape generate the same set of variant forms with different words in
    them, so the second re-runs the first one's check at the cost of every
    variant it parses.

    Two dimensions, enumerated rather than sampled:

    - **Shape**, keyed by (rule; per template its word count and whether it
      carries a diacritic; and how many of the rule's templates render to
      *distinct* strings). The diacritic flag is not decoration: it is what
      makes the "diacritics" respelling applicable at all, so a shape
      without one generates a strictly smaller variant set. Nor is the
      distinct count -- 0 renders "bial" for both its standalone and its
      bound form, so the units rule collapses to one spelling there and to
      two everywhere else. Without that term the class picks 0 as its
      representative and stops exercising the engine's single-placeholder
      leniency at all; a mutation disabling leniency escaped the sweep
      until this was added.
    - **Position in the range**, which is why supports.min and supports.max
      are always included even when their shape is already covered. They are
      the bounds text_to_number checks a value against, where an off-by-one
      lives; that is a different failure from anything shape covers.

    What this does *not* weaken is per-number correctness. Every number
    numbers_to_cover lists -- all of 0-999, and one of each shape above --
    is still round-tripped and still has its certified spellings parsed, by
    test_round_trip_number_text_number and the vector-driven tests. Those
    carry the lexical guarantee; this carries the structural one, and only
    the structural one needs every shape rather than every number.

    It is computed rather than listed, so a spec growing new rules or new
    collapsed-form cases grows new representatives on its own. It picks
    from numbers_to_cover, which already holds one number of every shape
    (_shape_representatives), so nothing here walks the range.
    """
    representatives = {}
    for n in numbers_to_cover(spec):
        representatives.setdefault(_shape(spec, n), n)
    bounds = {spec.supports["min"], spec.supports["max"]}
    return sorted(set(representatives.values()) | bounds)


def accepted_inputs(spec, n: int, every_dimension: bool = False) -> list:
    """The spellings of `n` that text_to_number() must accept.

    These are *representative* accepted spellings, one per applicable parse
    feature -- not every accepted spelling. Don't document them as if they
    were exhaustive; the two assumptions that make a representative list
    sufficient, and the point where each stops holding, are at the bottom of
    this docstring.

    The bounded rule, per entry:

    - the canonical output, verbatim -- the string number_to_text() returns,
      never a rebuild of it (see _joiners);
    - one variant per applicable respelling feature, applied to the
      canonical output: case, diacritics, alternate word separator, and the
      connector in each gap that is somewhere the connector can go and does
      not already hold one (see _connector_slots);
    - one combined variant with every applicable respelling applied at once,
      when more than one applies;
    - where the canonical output itself contains a connector, the spelling
      with it dropped (see _without_connectors);
    - one plain variant per alternate rendering: each `emit: never` rule
      that also describes n, and, for a freestanding single word, the other
      forms parse.accepted_forms allows.

    Not the cross product. One representative per feature is what makes a
    failure diagnostic: when a target fails an entry, the variant that failed
    names the feature that is broken. A cross product would report the same
    bug several dozen times and cost 18x the bytes for it.

    Connector placement is every gap where the connector idiomatically goes
    -- before a top-level addend after the first -- and no others, per #10,
    the #12 decision and Q-M on #27. Up to 99 that is one gap, which is why
    this used to be expressed as "the last gap"; from 100 up a number can
    have two, and "zâ leh sawm hnih leh pariat" (128) is idiomatic. The
    engine drops "leh" in *any* gap by deliberate design, but that is engine
    tolerance, not a target contract: listing every-gap forms would promote
    the tolerance into a requirement every future target must implement, for
    a string a Mizo speaker reads as "10 and 5 and 8" rather than as 58.
    Since #19 the canonical output can itself contain the connector, so the
    certified set also has to include the spelling with it dropped, and must
    not add a second one to a gap that already has it.

    Word separators are handled the same way, and for the same reason. The
    literal text a template puts between its placeholders is not necessarily
    the first effective separator -- English writes "forty-two" with a hyphen
    that is both literal output and a separator -- so the canonical string is
    taken from the renderer and the separator variant is an *alternate*
    joiner rather than "the second one in the list".

    Two assumptions hold this up, and both are load-bearing.

    First, that parse features compose, so covering each one separately
    covers them together. The engine's parse side is a pipeline -- normalise,
    split, drop connectors, resolve aliases, then match -- and each feature
    is one stage, so the assumption holds for the reference implementation
    and for #20's Python target, which is compiled from the same spec. It is
    not free, though: a target that reimplements parsing some other way could
    pass every entry here and still fail on a combination. The composition
    sweep that would catch that lives in test_engine.py, and a target cannot
    import it -- reference/ is not shipped. Pass every_dimension=True for the
    set that sweep consumes: every value of every dimension, varied one
    dimension at a time, plus a single fully-crossed representative. It is
    deliberately not the cross product -- see the every_dimension branch.

    Second, that an entry's accepted spellings can be enumerated at all.
    That is true of every parse feature in the spec today, and it stops being
    true above 10^5: Mizo scale words multiply each other productively there
    (nuai za hnih for 10^5 x 200), and any scale may take any
    scale-multiplied expression as its multiplier, so the accepted spellings
    of one number stop being a list and become a grammar. Nothing to do about
    it at 0-999, but whoever extends the range past that boundary will need
    generation from parse features to become generation from a grammar. See
    #27 for the data and #12 for the discussion.
    """
    separators = _joinable_separators(spec.parse_config)
    separator_pattern = _separator_pattern(spec.parse_config)

    canonical = spec.number_to_text(n)
    canonical_words = _split_words(canonical, separator_pattern)
    canonical_joiner, alternates = _joiners(canonical, canonical_words, separators)
    slots = _connector_slots(spec, n, canonical_words)
    features = _applicable_respellings(
        spec, canonical_words, bool(slots), alternates
    )

    variants = set()
    if every_dimension:
        # Each dimension varied on its own against an otherwise canonical
        # string, plus one fully-crossed representative -- not the cross
        # product of all three. This is not a claim about which strings are
        # Mizo; it is a check that the engine's tolerances genuinely compose.
        #
        # What licenses splitting them is structural, not a sampling
        # shortcut. engine._tokenize removes connectors before any matching,
        # so where the connector sits cannot reach the matcher at all:
        # placement is orthogonal to case, diacritics and separator choice by
        # construction. Crossing them re-verifies that one-line invariant
        # 2^gaps times per respelling.
        # test_connector_placement_does_not_survive_tokenisation asserts it
        # directly instead, which is what this split rests on (#27).
        #
        # "One dimension at a time" is exact *between* dimensions and loose
        # within two of them: _subsets(respellings) still crosses case with
        # diacritics, and _placements is three points rather than every
        # value. Both are bounded and neither is a product of the others,
        # which is the property that matters here.
        #
        # The one crossed row is the thing a pure per-dimension split would
        # lose: a target that handles each dimension alone but not in
        # combination. One row rather than 2^k of them.
        for words, joiner in _all_renderings(
            spec, n, separator_pattern, separators
        ):
            available = _connector_gaps(spec, words, ("connector",), (), every_gap=True)
            # Connector and separator are varied explicitly here -- by gap and
            # by joiner -- so neither is also varied as a respelling feature,
            # which would generate every string twice.
            respellings = [
                f
                for f in _applicable_respellings(spec, words, alternate_separators=separators)
                if f not in ("connector", "separator")
            ]
            alternate = next((s for s in separators if s != joiner), joiner)
            for subset in _subsets(respellings):
                variants.add(_respell(words, spec, subset, (), joiner))
            for gaps in _placements(available):
                variants.add(_respell(words, spec, (), gaps, joiner))
            for separator in separators:
                variants.add(_respell(words, spec, (), (), separator))
            variants.add(
                _respell(words, spec, tuple(respellings), available, alternate)
            )
    else:
        # The rendered string itself, not a rebuild of it from its words: a
        # template's literal text is not always the first effective separator,
        # and re-joining would drop the one string this list must contain.
        variants.add(canonical)
        for feature in features:
            gaps = _connector_gaps(spec, canonical_words, (feature,), slots)
            joiner = alternates[0] if feature == "separator" else canonical_joiner
            variants.add(_respell(canonical_words, spec, (feature,), gaps, joiner))
        if len(features) > 1:
            gaps = _connector_gaps(spec, canonical_words, features, slots)
            joiner = alternates[0] if "separator" in features else canonical_joiner
            variants.add(_respell(canonical_words, spec, features, gaps, joiner))
        # The connector-dropped spelling. Confirmed for 108 by the repo owner
        # (Q-D on #27) and across 111-199 by Rosie Malsawmtluangi (#19): where
        # canonical output emits "leh", leaving it out is equally idiomatic.
        # It only arises where the canonical output carries a connector, so
        # nothing below grammar.connector's `min` produces one.
        dropped = _without_connectors(spec, canonical_words)
        if len(dropped) != len(canonical_words):
            variants.add(canonical_joiner.join(dropped))
        variants.update(_alternate_renderings(spec, n))

    return sorted(variants)


def _alternate_renderings(spec, n: int) -> list:
    """Spellings of `n` other than its canonical output.

    Two sources. An `emit: never` rule at the scale n is rendered at, whose
    multiplier and condition hold for n, is accepted when parsing and never
    produced -- Mizo's shorthand "hnih thum" for 23. The other is the
    engine's leniency for a phrase that is a single freestanding word, which
    accepts any form parse.accepted_forms allows ("khat" as well as "pakhat"
    for 1).

    Which fields leniency allows comes from the engine rather than from a
    "standalone"/"bound" list written out here. That is why this kept
    working unchanged when #31 moved the decision into the spec, and why
    the vectors did not move.

    An `emit: never` rule is asked about n at the canonical rule's scale
    only. Its condition is written for that scale -- "multiplier > 1 and
    remainder > 0" is true of 150 at scale 10 too, and there is no fifteenth
    unit to render.
    """
    rule = spec._find_rule(n)
    multiplier, remainder = divmod(n, rule["scale"])
    renderings = []
    for other in spec.rules:
        if other.get("emit") != "never" or other["scale"] != rule["scale"]:
            continue
        if spec._rule_applies(other, multiplier, remainder):
            text, boundaries = spec._render_rule(other, n)
            renderings.append(spec._with_connector(n, text, boundaries))

    words = _single_lexicon_word(spec, rule, remainder)
    if words is not None:
        table, key, field = words
        value = {"multiplier": multiplier, "remainder": remainder}.get(key, key)
        entry = spec.lexicon[table][value]
        for other in spec._acceptable_fields(table, field, lenient=True):
            if other != field and other in entry:
                renderings.append(entry[other])
    return renderings


def _single_lexicon_word(spec, rule, remainder: int):
    """(table, key, field) when `rule` renders n as one lexicon word, else None.

    That is the only shape leniency applies to, and it depends on n as well
    as the rule: `ten` is one word for 10 and two for 11, because its [...]
    segment is present exactly when the remainder is.
    """
    items = []
    for item in spec._items[id(rule)]:
        if isinstance(item, tuple) and item[0] == "optional":
            if remainder:
                items.extend(item[1])
        else:
            items.append(item)
    placeholders = [item for item in items if not isinstance(item, str)]
    if len(placeholders) != 1 or placeholders[0][0] != "lex":
        return None
    _, table, key, field = placeholders[0]
    return table, key, field


def _applicable_respellings(
    spec, words, connector_allowed: bool = True, alternate_separators=()
) -> tuple:
    """Which respelling features actually produce something for this phrase.

    Applicability is checked rather than left to deduplication, because a
    feature that cannot apply must not be counted as covered: "sawm hnih"
    has no diacritics to strip, and a single-word phrase has no gap to put a
    connector or an alternate separator in. The same reasoning is why
    connector_allowed is threaded through here rather than only suppressing
    the gap: if the feature still counted as applicable, the combined
    variant would quietly lose its connector and the file would claim
    coverage it doesn't have.

    alternate_separators is passed in rather than read off the spec because
    "is there another separator" is a question about this phrase, not about
    the language: it means "another separator than the one the canonical
    rendering already uses". See _joiners.
    """
    parse = spec.parse_config
    features = []
    if parse.get("case_insensitive", False):
        features.append("case")
    if parse.get("strip_diacritics", False) and any(w != _strip_diacritics(w) for w in words):
        features.append("diacritics")
    if alternate_separators and len(words) > 1:
        features.append("separator")
    if parse.get("connectors") and len(words) > 1 and connector_allowed:
        features.append("connector")
    return tuple(features)


def _joiners(canonical: str, words, separators) -> tuple:
    """The separator the canonical rendering uses, and the alternates to it.

    A template's placeholders are joined by whatever literal text sits
    between them, which is not necessarily the first effective separator
    (_joinable_separators, whitespace first since #46): English renders 42 as
    "forty-two", where the hyphen is both literal output and a separator
    (docs/spec-format.md). Treating the first separator as
    canonical produced "forty two" as the "canonical" variant and left the
    real one to arrive by luck, as the alternate-separator variant, which
    only worked because the hyphen happened to be second in en.yaml's list.

    Detected by asking which separator reproduces the rendered string,
    rather than by parsing the template, so a language whose literal text
    isn't a separator at all falls through to the first one and simply gets
    no separator variant.
    """
    used = next((s for s in separators if s.join(words) == canonical), separators[0])
    return used, [s for s in separators if s != used]


def _connectors(spec) -> set:
    """The spec's connector words, normalised, as a set."""
    return {spec._normalize_word(c) for c in spec.parse_config.get("connectors", [])}


def _connector_slots(spec, n: int, words) -> tuple:
    """Which gaps between `words` a connector may idiomatically be added to.

    Two independent questions.

    1. Is this gap a place a connector belongs? The linguistic fact, from
       the repo owner as a native speaker (#34, and Q-E on #27): "leh"
       precedes a *top-level addend*, never a bound digit inside one. So
       "sâwm leh pakhat" (11) and "sawm nga leh pariat" (58) are Mizo, while
       "sawm leh hnih" (20) and "zâ sawm leh thum" (130) are not -- the
       trailing digit there multiplies the scale word rather than adding to
       it. Confirmed for 100-199 by Rosie Malsawmtluangi (#19), and for
       200-999 by the same speaker on #27 (Q-N).

       Read from the grammar, not declared beside it. Every addend after the
       first begins where a {remainder} expansion begins, so the renderer's
       boundaries (Spec._render_rule) are exactly the gaps in question. Until
       #65 this was a separate declaration, parse.connector_precedes, naming
       the lexicon fields that begin an addend, and the generator lined
       template positions up with rendered words to find them. That
       alignment stopped working the moment a placeholder could render to
       several words, which {remainder} does; the boundaries give the same
       gaps for all 1,000 numbers without it. A language gets them only if
       it declares grammar.connector: English drops "and" on input but
       certifies no connector position, so "forty and two" is not blessed.

    2. Is the gap still empty? From 100 up the canonical output itself
       contains "leh", before the final addend (Q-M on #27). A gap whose
       neighbour is already a connector is spoken for; adding another
       produces "zâ leh leh pariat", which is not Mizo and which nothing
       downstream would catch -- the generator's own parse-back check passes
       it, since _tokenize drops connectors however many there are.

    The certified set stays deliberately narrower than what the engine
    tolerates (#12, #34): the engine drops a connector from any gap, so it
    parses strings this never certifies.
    """
    connectors = _connectors(spec)
    if spec.connector is None or not connectors or len(words) < 2:
        return ()

    rule = spec._find_rule(n)
    bare, boundaries = spec._render_rule(rule, n)
    pattern = _separator_pattern(spec.parse_config)
    # The word each addend starts at, counted in the rendering without a
    # connector. The canonical words differ from that only by the connector
    # before the final addend, so every earlier start has the same index in
    # both. The final start, when a connector was written there, has "leh" as
    # its right-hand neighbour in the canonical words -- which is question 2
    # below, asked of the words themselves, so it also covers a connector
    # written into a template literal.
    starts = sorted({len(_split_words(bare[:at], pattern)) for at in boundaries})

    slots = []
    for start in starts:
        gap = start - 1
        if gap < 0:
            continue                      # an addend at the first word has no gap before it
        if any(spec._normalize_word(w) in connectors for w in (words[gap], words[gap + 1])):
            continue                      # gap already holds a connector
        slots.append(gap)
    return tuple(slots)


def _respell(words, spec, features, connector_gaps, joiner) -> str:
    """Write one phrase a different way, without changing which number it is.

    Order matters: the connector goes in before normalisation, so that it
    gets the same casing as the rest of the phrase rather than staying
    lowercase in an otherwise uppercase string.

    The joiner is chosen by the caller rather than derived from `features`,
    because which separator counts as "the alternate one" depends on which
    one the canonical rendering already used (see _joiners).
    """
    parse = spec.parse_config

    out = []
    for i, word in enumerate(words):
        out.append(word)
        if i in connector_gaps:
            out.append(parse["connectors"][0])
    if "diacritics" in features:
        out = [_strip_diacritics(w) for w in out]
    if "case" in features:
        out = [w.upper() for w in out]

    return joiner.join(out)


def _without_connectors(spec, words) -> list:
    """`words` with any connector word removed."""
    connectors = _connectors(spec)
    return [w for w in words if spec._normalize_word(w) not in connectors]


def _connector_gaps(spec, words, features, slots, every_gap: bool = False) -> tuple:
    """Which gaps between words the connector may be inserted into.

    `slots` comes from _connector_slots() -- the gaps that are both a place
    a connector belongs and not already occupied by one. Unless every_gap,
    which ignores the question and returns them all; see accepted_inputs()
    for why the certified set is narrower than what the engine tolerates.

    `slots` is required rather than defaulted. It used to default to (), so a
    caller who forgot it silently certified *fewer* spellings than it meant to
    -- a quiet under-generation rather than an error. The every_gap caller
    passes () explicitly, because that path ignores slots by design.
    """
    if "connector" not in features or not spec.parse_config.get("connectors") or len(words) < 2:
        return ()
    if every_gap:
        return tuple(range(len(words) - 1))
    return tuple(slots)


def _all_renderings(spec, n: int, separator_pattern, separators) -> list:
    """Each spelling of n the rules produce -- canonical first, then the
    alternates -- as (words, the joiner that rendering used).

    The joiner is asked for rather than assumed, for the same reason _joiners
    exists: a template's literal text is not necessarily the first effective
    separator, so rebuilding a rendering with a guessed joiner can produce a
    string the template never emits.
    """
    renderings = []
    for rendered in [spec.number_to_text(n), *_alternate_renderings(spec, n)]:
        words = _split_words(rendered, separator_pattern)
        used, _ = _joiners(rendered, words, separators)
        renderings.append((words, used))
    return renderings


def _placements(gaps) -> tuple:
    """Connector placements to sweep: none, each gap alone, and every gap.

    Linear in the number of gaps rather than the power set of them. Every
    subset reduces to the same token list -- that is exactly what
    test_connector_placement_does_not_survive_tokenisation pins -- so
    enumerating all 2^gaps of them spends exponential time re-verifying a
    one-line invariant that is asserted directly elsewhere (#27, and the
    review of #58).

    The power set is not gone, it moved: the invariant test still walks
    every subset, over one representative per shape class, and each step
    there costs a tokenisation rather than a parse -- no range scan, so no
    growth with supports.max. What is dropped here is re-deriving the same
    fact through the parser once per number in range.

    Which three points, and why not two. Against connectors-never-stripped,
    case-folding-dropped and diacritics-dropped, `none` and `all` alone
    catch everything the singles do -- three mutations is not a proof, but
    no measurement here says the singles find defects. They stay for a
    different reason: they are the only rows exhibiting the *partial*
    placement that Q-P on #27 licenses ("a partial sprinkle is licensed
    too"), which `none` and `all` between them never show. Accept-set
    documentation rather than coverage, and cheap enough to keep.

    Sized against a 5-gap ceiling: at supports.max 999 the longest canonical
    output is six words (221, "za hnih sawm hnih leh pakhat"), and 576 of the
    1,000 numbers sit at that ceiling rather than below it. The power set
    this replaces was 32 rows there -- 16 at the 4-gap ceiling of 199 -- and
    2,048 at the 12-word forms of 10^6; this helper is 7, 6 and 13. When
    accepted spellings stop being a list and become a grammar (steps 3-4 of
    #27), "vary the placement" stops being a subset-of-gaps at all and this
    helper should go with it.
    """
    gaps = tuple(gaps)
    if not gaps:
        return ((),)
    singles = tuple((gap,) for gap in gaps)
    every = (gaps,) if len(gaps) > 1 else ()
    return ((),) + singles + every


def _subsets(items) -> list:
    items = tuple(items)
    return [
        combo
        for size in range(len(items) + 1)
        for combo in itertools.combinations(items, size)
    ]


def _split_words(text: str, separator_pattern: str) -> list:
    return [word for word in re.split(separator_pattern, text) if word]


def build_vectors(spec) -> list:
    """Build the vector table, checking every string it writes.

    Each accepted input is parsed back before it is written. A vector that
    doesn't parse is worse than a missing one -- it would be checked into
    git and every target would then be required to accept a string the
    oracle itself rejects -- so this fails loudly at generation time rather
    than shipping it.
    """
    vectors = []
    for n in numbers_to_cover(spec):
        text = spec.number_to_text(n)
        inputs = accepted_inputs(spec, n)
        for candidate in inputs:
            parsed = spec.text_to_number(candidate)
            if parsed != n:
                raise AssertionError(
                    f"generated accepted input {candidate!r} for n={n} parses back as {parsed}"
                )
        # Entries stay in numeric order; only accepted_inputs is sorted, so
        # that the file is byte-stable for the CI drift check. Sorting the
        # entries themselves would order them as strings ("10" before "2").
        vectors.append({"number": str(n), "text": text, "accepted_inputs": inputs})
    return vectors


def main() -> None:
    spec = load(SPEC_PATH)
    vectors = build_vectors(spec)
    VECTORS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(VECTORS_PATH, "w", encoding="utf-8") as f:
        json.dump(vectors, f, ensure_ascii=False, indent=2)
        f.write("\n")
    total = sum(len(v["accepted_inputs"]) for v in vectors)
    print(
        f"Wrote {len(vectors)} vectors ({total} accepted inputs) to "
        f"{VECTORS_PATH.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
