"""Generates vectors/mizo.json -- the conformance vectors described in
docs/architecture.md: a checked-in table for the full supported range,
generated from the reference engine (the oracle), that every target package
will eventually be tested against.

Run from inside reference/ (same convention as pytest, see README.md):

    python generate_vectors.py

Regenerate and commit vectors/mizo.json whenever languages/mizo.yaml's
lexicon or grammar changes -- it's a snapshot, not computed at test time, so
test_engine.py can catch a spec edit that silently changed output and wasn't
followed by a regenerate.

Each entry has three fields:

    { "number": "58",
      "text": "sawm nga pariat",
      "accepted_inputs": [ ... ] }

`text` is the canonical output: what number_to_text() must produce.
`accepted_inputs` is what text_to_number() must accept, and it includes
`text` itself, so a target can iterate one field rather than remembering to
also test the canonical form. See below for how the list is chosen.

Why `number` is a string (#12)
------------------------------
Every number in this file today is between 0 and 100, so JSON's number type
would do. It is written as a string anyway, because the format outlives the
range. #27 sets Mizo's eventual ceiling at 10^18 - 1, which is 111x larger
than JavaScript's Number.MAX_SAFE_INTEGER: a standard JSON.parse reads
999999999999999999 back as 1000000000000000000. A JS target would then load
the vectors, compare its output against a silently wrong expected value, and
pass -- a conformance suite that certifies a broken implementation is worse
than no suite at all. Python's arbitrary-precision ints hide this, so it
would go unnoticed until the npm target exists, by which point the format is
fixed and every vectors file needs regenerating. Deciding it now costs one
str() here and an int() in the tests.
"""

import itertools
import json
import re
from pathlib import Path

# These are engine internals, imported deliberately rather than reimplemented.
# The vectors are only meaningful if they are generated by the same rule
# selection, rendering and leniency the engine itself uses -- a local copy
# would drift, and the drift would show up as vectors that certify behaviour
# the oracle doesn't have. If this private surface grows further, promote it
# to public methods on Spec rather than widening the import.
from engine import (
    _PLACEHOLDER_RE,
    _find_rule,
    _positional_variables,
    _render,
    _strip_diacritics,
    load,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT / "languages" / "mizo.yaml"
VECTORS_PATH = REPO_ROOT / "vectors" / "mizo.json"


def numbers_to_cover(spec) -> list:
    """Which numbers get an entry in the vectors file.

    Today: every number in the supported range, which is 0-199 since #19,
    and it stays exhaustive. The policy agreed in #12 for when it stops
    being exhaustive:

    - Enumerate every number while the range is under roughly 1,000 entries.
      The threshold is arbitrary -- writing it down is the point, so that
      growing past it is a decision rather than a surprise.
    - Above that, sample one entry per structural case rather than one per
      number, using the list in #27: each scale boundary and the numbers
      either side of it, the x1 cases, the 10^2/10^3 behavioural split,
      numbers with zero digits in the middle, and supports.max itself.

    This exists as a named function so #19 and whatever follows it edit one
    function instead of restructuring the generator. Which numbers get an
    entry and which spellings each entry accepts are independent decisions:
    sampling picks the rows, accepted_inputs() fills them in, and the rule
    it uses is per-entry so it already works at any range.
    """
    return list(range(spec.supports["min"], spec.supports["max"] + 1))


def accepted_inputs(spec, n: int, exhaustive: bool = False) -> list:
    """The spellings of `n` that text_to_number() must accept.

    These are *representative* accepted spellings, one per applicable parse
    feature -- not every accepted spelling. Don't document them as if they
    were exhaustive; the two assumptions that make a representative list
    sufficient, and the point where each stops holding, are at the bottom of
    this docstring.

    The bounded rule, per entry:

    - the canonical output, verbatim -- the string number_to_text() returns,
      never a rebuild of it (see _joiners);
    - one variant per applicable respelling feature, applied to the
      canonical output: case, diacritics, alternate word separator, and the
      connector in each gap that is somewhere the connector can go and does
      not already hold one (see _connector_slots);
    - one combined variant with every applicable respelling applied at once,
      when more than one applies;
    - where the canonical output itself contains a connector, the spelling
      with it dropped (see _without_connectors);
    - one plain variant per alternate template: each of the rule's
      parse_aliases, and, for a freestanding single digit, the other unit
      forms parse.accepted_forms allows.

    Not the cross product. One representative per feature is what makes a
    failure diagnostic: when a target fails an entry, the variant that failed
    names the feature that is broken. A cross product would report the same
    bug several dozen times and cost 18x the bytes for it.

    Connector placement is every gap where the connector idiomatically goes
    -- before a top-level addend after the first -- and no others, per #10,
    the #12 decision and Q-M on #27. Up to 99 that is one gap, which is why
    this used to be expressed as "the last gap"; from 100 up a number can
    have two, and "zâ leh sawm hnih leh pariat" (128) is idiomatic. The
    engine drops "leh" in *any* gap by deliberate design, but that is engine
    tolerance, not a target contract: listing every-gap forms would promote
    the tolerance into a requirement every future target must implement, for
    a string a Mizo speaker reads as "10 and 5 and 8" rather than as 58.
    Since #19 the canonical output can itself contain the connector, so the
    certified set also has to include the spelling with it dropped, and must
    not add a second one to a gap that already has it.

    Word separators are handled the same way, and for the same reason. The
    literal text a template puts between its placeholders is not necessarily
    word_separators[0] -- English writes "forty-two" with a hyphen that is
    both literal output and a separator -- so the canonical string is taken
    from the renderer and the separator variant is an *alternate* joiner
    rather than "the second one in the list".

    Two assumptions hold this up, and both are load-bearing.

    First, that parse features compose, so covering each one separately
    covers them together. The engine's parse side is a pipeline -- normalise,
    split, drop connectors, resolve aliases, then match -- and each feature
    is one stage, so the assumption holds for the reference implementation
    and for #20's Python target, which is compiled from the same spec. It is
    not free, though: a target that reimplements parsing some other way could
    pass every entry here and still fail on a combination. The exhaustive
    sweep that would catch that lives in test_engine.py, and a target cannot
    import it -- reference/ is not shipped. Pass exhaustive=True to generate
    the full cross product.

    Second, that an entry's accepted spellings can be enumerated at all.
    That is true of every parse feature in the spec today, and it stops being
    true above 10^5: Mizo scale words multiply each other productively there
    (nuai za hnih for 10^5 x 200), and any scale may take any
    scale-multiplied expression as its multiplier, so the accepted spellings
    of one number stop being a list and become a grammar. Nothing to do about
    it at 0-199, but whoever extends the range past that boundary will need
    generation from parse features to become generation from a grammar. See
    #27 for the data and #12 for the discussion.
    """
    variables = _positional_variables(n)
    rule = _find_rule(spec.rules, n, variables)
    separators = spec.parse_config.get("word_separators", [" "])

    canonical = _render(rule["output"], spec.lexicon, variables)
    canonical_words = _split_words(canonical, separators)
    canonical_joiner, alternates = _joiners(canonical, canonical_words, separators)
    slots = _connector_slots(spec, rule, canonical_words)
    features = _applicable_respellings(
        spec, canonical_words, bool(slots), alternates
    )

    variants = set()
    if exhaustive:
        # Every template crossed with every subset of respellings, with the
        # connector in every subset of gaps rather than only the last, and
        # joined by every separator rather than only an alternate one. This
        # is not a claim about which strings are Mizo -- it is a check that
        # the engine's tolerances genuinely compose.
        for words in _all_renderings(spec, rule, variables, separators):
            available = _connector_gaps(spec, words, ("connector",), (), every_gap=True)
            # Connector and separator are varied explicitly here -- by gap and
            # by joiner -- so neither is also varied as a respelling feature,
            # which would generate every string twice.
            respellings = [
                f
                for f in _applicable_respellings(spec, words, alternate_separators=separators)
                if f not in ("connector", "separator")
            ]
            for subset in _subsets(respellings):
                for gaps in _subsets(available):
                    for joiner in separators:
                        variants.add(_respell(words, spec, subset, gaps, joiner))
    else:
        # The rendered string itself, not a rebuild of it from its words: a
        # template's literal text is not always word_separators[0], and
        # re-joining would drop the one string this list must contain.
        variants.add(canonical)
        for feature in features:
            gaps = _connector_gaps(spec, canonical_words, (feature,), slots)
            joiner = alternates[0] if feature == "separator" else canonical_joiner
            variants.add(_respell(canonical_words, spec, (feature,), gaps, joiner))
        if len(features) > 1:
            gaps = _connector_gaps(spec, canonical_words, features, slots)
            joiner = alternates[0] if "separator" in features else canonical_joiner
            variants.add(_respell(canonical_words, spec, features, gaps, joiner))
        # The connector-dropped spelling. Confirmed for 108 by the repo owner
        # (Q-D on #27) and across 111-199 by Rosie Malsawmtluangi (#19): where
        # canonical output emits "leh", leaving it out is equally idiomatic.
        # It only arises once a template carries a literal connector, so
        # nothing below 100 produces one.
        dropped = _without_connectors(spec, canonical_words)
        if len(dropped) != len(canonical_words):
            variants.add(canonical_joiner.join(dropped))
        for template in _alternate_templates(spec, rule):
            variants.add(_render(template, spec.lexicon, variables))

    return sorted(variants)


def _alternate_templates(spec, rule) -> list:
    """Templates for `n` other than its canonical output.

    Two sources. `parse_aliases` are declared per rule -- extra templates
    accepted when parsing and never produced by number_to_text(), e.g.
    compound_tens' shorthand that drops the scale word. The other is the
    engine's leniency for a phrase that is a single freestanding
    placeholder, which accepts any unit form parse.accepted_forms allows
    ("khat" as well as "pakhat" for 1). That one is expressed here as a
    synthetic template with the field name swapped, so both sources go
    through the same render path.

    Which fields leniency allows comes from the engine rather than from a
    "standalone"/"bound" list written out here. That is why this kept
    working unchanged when #31 moved the decision into the spec, and why
    the vectors did not move.
    """
    templates = list(rule.get("parse_aliases", []))

    placeholders = _PLACEHOLDER_RE.findall(rule["output"])
    if len(placeholders) == 1:
        table, raw_key, field = placeholders[0]
        for other in spec._acceptable_fields(table, field, lenient=True):
            if other != field:
                templates.append("{%s[%s].%s}" % (table, raw_key, other))
    return templates


def _applicable_respellings(
    spec, words, connector_allowed: bool = True, alternate_separators=()
) -> tuple:
    """Which respelling features actually produce something for this phrase.

    Applicability is checked rather than left to deduplication, because a
    feature that cannot apply must not be counted as covered: "sawm hnih"
    has no diacritics to strip, and a single-word phrase has no gap to put a
    connector or an alternate separator in. The same reasoning is why
    connector_allowed is threaded through here rather than only suppressing
    the gap: if the feature still counted as applicable, the combined
    variant would quietly lose its connector and the file would claim
    coverage it doesn't have.

    alternate_separators is passed in rather than read off the spec because
    "is there another separator" is a question about this phrase, not about
    the language: it means "another separator than the one the canonical
    rendering already uses". See _joiners.
    """
    parse = spec.parse_config
    features = []
    if parse.get("case_insensitive", False):
        features.append("case")
    if parse.get("strip_diacritics", False) and any(w != _strip_diacritics(w) for w in words):
        features.append("diacritics")
    if alternate_separators and len(words) > 1:
        features.append("separator")
    if parse.get("connectors") and len(words) > 1 and connector_allowed:
        features.append("connector")
    return tuple(features)


def _joiners(canonical: str, words, separators) -> tuple:
    """The separator the canonical rendering uses, and the alternates to it.

    A template's placeholders are joined by whatever literal text sits
    between them, which is not necessarily word_separators[0]: English
    renders 42 as "forty-two", where the hyphen is both literal output and a
    separator (docs/spec-format.md). Treating the first separator as
    canonical produced "forty two" as the "canonical" variant and left the
    real one to arrive by luck, as the alternate-separator variant, which
    only worked because the hyphen happened to be second in en.yaml's list.

    Detected by asking which separator reproduces the rendered string,
    rather than by parsing the template, so a language whose literal text
    isn't a separator at all falls through to the first one and simply gets
    no separator variant.
    """
    used = next((s for s in separators if s.join(words) == canonical), separators[0])
    return used, [s for s in separators if s != used]


def _template_tokens(spec, rule) -> list:
    """The rule's output template split into word-sized tokens, in order.

    Each token is either a whole placeholder or a literal word. Callers use
    it to line template positions up with rendered words, so they must check
    the two lists are the same length rather than zip them -- a lexicon
    value containing a separator would break the correspondence silently.
    """
    separators = spec.parse_config.get("word_separators", [" "])
    pattern = "|".join(re.escape(sep) for sep in separators)
    return [token for token in re.split(pattern, rule["output"]) if token]


def _connectors(spec) -> set:
    """The spec's connector words, normalised, as a set."""
    return {spec._normalize_word(c) for c in spec.parse_config.get("connectors", [])}


def _connector_slots(spec, rule, words) -> tuple:
    """Which gaps between `words` a connector may idiomatically be added to.

    Two independent questions, and #19 is the first range where they give
    different answers, so they are now asked separately.

    1. Is this gap a place a connector belongs? The linguistic fact, from
       the repo owner as a native speaker (#34, and Q-E on #27): "leh"
       precedes a *top-level addend*, never a bound digit inside one. So
       "sâwm leh pakhat" (11) and "sawm nga leh pariat" (58) are Mizo, while
       "sawm leh hnih" (20) and "zâ sawm leh thum" (130) are not -- the
       trailing digit there multiplies the scale word rather than adding to
       it. Confirmed for 100-199 by Rosie Malsawmtluangi (#19).

       Declared, not inferred: parse.connector_precedes names the lexicon
       fields that begin a top-level addend, and this function only looks
       that declaration up. Inferring it here meant one of two bad options.
       Keying off the field names "standalone"/"bound" would hardcode Mizo's
       vocabulary into language-agnostic code, which is what #31 removed;
       reading template positions was a proxy with a known expiry, since the
       recursive multiplier at 10^9 gives "the next addend up" a shape no
       positional test can see (#27). #19 retired the proxy rather than
       widening it.

    2. Is the gap still empty? From #19 the canonical output itself contains
       "leh", because the output convention emits it before the final addend
       (Q-M on #27). A gap whose neighbour is already a connector is spoken
       for; adding another produces "zâ leh leh pariat", which is not Mizo
       and which nothing downstream would catch -- the generator's own
       parse-back check passes it, since _tokenize drops connectors however
       many there are.

    The certified set stays deliberately narrower than what the engine
    tolerates (#12, #34): the engine drops a connector from any gap, so it
    parses strings this never certifies. Nothing here decides that -- the
    spec does, by naming only the fields a connector may precede.
    """
    connectors = _connectors(spec)
    precedes = spec.parse_config.get("connector_precedes", {})
    if not connectors or not precedes or len(words) < 2:
        return ()

    tokens = _template_tokens(spec, rule)
    if len(tokens) != len(words):
        # A placeholder rendered to something other than one word, so
        # template position and word position no longer correspond. Say so
        # instead of certifying gaps computed from a bad alignment.
        raise ValueError(
            "template/word mismatch for rule %r: %d tokens, %d words"
            % (rule["name"], len(tokens), len(words))
        )

    slots = []
    for i in range(len(words) - 1):
        placeholder = _PLACEHOLDER_RE.fullmatch(tokens[i + 1])
        if placeholder is None:
            continue                      # a literal follows; not an addend boundary
        table, _raw_key, field = placeholder.groups()
        # The spec says which forms begin an addend; a form it does not name
        # is a digit bound to the scale word before it, which a connector
        # must not split.
        if field not in precedes.get(table, ()):
            continue
        # Only words[i] can hit on today's data: the loop has already
        # established that tokens[i + 1] is a placeholder, so words[i + 1] is a
        # rendered lexicon value, and no entry in either spec is spelled like a
        # connector. The forward half is kept deliberately -- a language may
        # well name a numeral the way it names its connector, and skipping that
        # gap is the right answer there too.
        if any(spec._normalize_word(w) in connectors for w in (words[i], words[i + 1])):
            continue                      # gap already holds a connector
        slots.append(i)
    return tuple(slots)


def _respell(words, spec, features, connector_gaps, joiner) -> str:
    """Write one phrase a different way, without changing which number it is.

    Order matters: the connector goes in before normalisation, so that it
    gets the same casing as the rest of the phrase rather than staying
    lowercase in an otherwise uppercase string.

    The joiner is chosen by the caller rather than derived from `features`,
    because which separator counts as "the alternate one" depends on which
    one the canonical rendering already used (see _joiners).
    """
    parse = spec.parse_config

    out = []
    for i, word in enumerate(words):
        out.append(word)
        if i in connector_gaps:
            out.append(parse["connectors"][0])
    if "diacritics" in features:
        out = [_strip_diacritics(w) for w in out]
    if "case" in features:
        out = [w.upper() for w in out]

    return joiner.join(out)


def _without_connectors(spec, words) -> list:
    """`words` with any connector word removed."""
    connectors = _connectors(spec)
    return [w for w in words if spec._normalize_word(w) not in connectors]


def _connector_gaps(spec, words, features, slots, every_gap: bool = False) -> tuple:
    """Which gaps between words the connector may be inserted into.

    `slots` comes from _connector_slots() -- the gaps that are both a place
    a connector belongs and not already occupied by one. Unless every_gap,
    which ignores the question and returns them all; see accepted_inputs()
    for why the certified set is narrower than what the engine tolerates.

    `slots` is required rather than defaulted. It used to default to (), so a
    caller who forgot it silently certified *fewer* spellings than it meant to
    -- a quiet under-generation rather than an error. The every_gap caller
    passes () explicitly, because that path ignores slots by design.
    """
    if "connector" not in features or not spec.parse_config.get("connectors") or len(words) < 2:
        return ()
    if every_gap:
        return tuple(range(len(words) - 1))
    return tuple(slots)


def _all_renderings(spec, rule, variables, separators) -> list:
    templates = [rule["output"], *_alternate_templates(spec, rule)]
    return [_split_words(_render(t, spec.lexicon, variables), separators) for t in templates]


def _subsets(items) -> list:
    items = tuple(items)
    return [
        combo
        for size in range(len(items) + 1)
        for combo in itertools.combinations(items, size)
    ]


def _split_words(text: str, separators) -> list:
    pattern = "|".join(re.escape(sep) for sep in separators)
    return [word for word in re.split(pattern, text) if word]


def build_vectors(spec) -> list:
    """Build the vector table, checking every string it writes.

    Each accepted input is parsed back before it is written. A vector that
    doesn't parse is worse than a missing one -- it would be checked into
    git and every target would then be required to accept a string the
    oracle itself rejects -- so this fails loudly at generation time rather
    than shipping it.
    """
    vectors = []
    for n in numbers_to_cover(spec):
        text = spec.number_to_text(n)
        inputs = accepted_inputs(spec, n)
        for candidate in inputs:
            parsed = spec.text_to_number(candidate)
            if parsed != n:
                raise AssertionError(
                    f"generated accepted input {candidate!r} for n={n} parses back as {parsed}"
                )
        # Entries stay in numeric order; only accepted_inputs is sorted, so
        # that the file is byte-stable for the CI drift check. Sorting the
        # entries themselves would order them as strings ("10" before "2").
        vectors.append({"number": str(n), "text": text, "accepted_inputs": inputs})
    return vectors


def main() -> None:
    spec = load(SPEC_PATH)
    vectors = build_vectors(spec)
    VECTORS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(VECTORS_PATH, "w", encoding="utf-8") as f:
        json.dump(vectors, f, ensure_ascii=False, indent=2)
        f.write("\n")
    total = sum(len(v["accepted_inputs"]) for v in vectors)
    print(
        f"Wrote {len(vectors)} vectors ({total} accepted inputs) to "
        f"{VECTORS_PATH.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
