"""Tests for the reference engine (engine.py). Two independent artifacts are
checked against, on purpose, because they prove different things:

- mizo.yaml's examples: block -- 18 pairs a native speaker wrote by hand.
  Independent ground truth: catches a numeral that's simply wrong.
- vectors/mizo.json -- generated from the engine by generate_vectors.py and
  checked into git; it is NOT regenerated by these tests. Catches drift: a
  spec edit whose output changed without a regenerate. It canNOT catch a
  wrong-but-dutifully-regenerated numeral, since it's generated from the
  same engine it's tested against -- that's what the examples: test is for.
  Each entry also carries accepted_inputs: representative spellings
  text_to_number() must accept, one per applicable parse feature (#12). That
  is the half of the contract `text` alone can't state -- a target package
  can match every canonical string and still reject everything a Mizo
  speaker types. See generate_vectors.accepted_inputs() for the rule.

mizo.yaml's core numeral data has been verified by a native Mizo speaker
(see meta.sources). The "leh" connector (parse.connectors) is a separate,
deliberate exception -- not unverified, but a documented team decision to
leave it unresolved (see mizo.yaml's header and its `# Decision (#10)` tag).
Nothing in mizo.yaml is marked TODO(verify) as of #15: parse.aliases was the
last one, and its diacritic part is now handled by parse.strip_diacritics.
These tests check that the engine correctly follows the grammar as written,
not whether the grammar itself is linguistically correct.
"""

import copy
import json
import re
from pathlib import Path

import pytest

import generate_vectors
from engine import Spec, load

MIZO_SPEC_PATH = Path(__file__).resolve().parent.parent / "languages" / "mizo.yaml"
VECTORS_PATH = Path(__file__).resolve().parent.parent / "vectors" / "mizo.json"

# mizo.yaml's meta.supports.max, stated here rather than read from the spec:
# these tests are meant to be an independent claim about what must work, so
# a spec edit that narrowed the range should fail them rather than shrink
# them. Widen it in the same PR that widens the spec (#19).
SUPPORTED_MAX = 199


@pytest.fixture(scope="module")
def spec():
    return load(MIZO_SPEC_PATH)


@pytest.fixture(scope="module")
def vectors():
    with open(VECTORS_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def test_examples_match(spec):
    # mizo.yaml's examples: are hand-written by a native speaker -- the
    # independent anchor. vectors/mizo.json is generated from the engine,
    # so it can only catch drift, never a wrong-but-regenerated numeral.
    for example in spec.examples:
        assert spec.number_to_text(example["number"]) == example["text"], f"n={example['number']}"


def test_vectors_match_number_to_text(spec, vectors):
    for vector in vectors:
        n = int(vector["number"])
        assert spec.number_to_text(n) == vector["text"], f"n={n}"


def test_vector_numbers_are_strings(vectors):
    # #12: `number` is deliberately a string, so that a JS target reading
    # this file cannot silently lose precision above 2^53 - 1 once the range
    # grows (#27 puts Mizo's ceiling at 10^18 - 1). Nothing in the current
    # 0-199 range needs it; the format does. Asserted so that a future
    # regenerate cannot quietly drop back to a JSON number.
    for vector in vectors:
        assert isinstance(vector["number"], str), vector


@pytest.mark.parametrize("n", range(0, SUPPORTED_MAX + 1))
def test_every_number_in_range_has_a_matching_rule(spec, n):
    # Every number in the supported range must match some grammar rule --
    # this catches gaps/overlaps in rule ranges even for numbers we don't
    # have a hand-written example for.
    spec.number_to_text(n)


def test_out_of_range_raises(spec):
    with pytest.raises(ValueError):
        spec.number_to_text(SUPPORTED_MAX + 1)
    with pytest.raises(ValueError):
        spec.number_to_text(-1)


def test_vectors_parse_back(spec, vectors):
    for vector in vectors:
        assert spec.text_to_number(vector["text"]) == int(vector["number"])


def test_every_accepted_input_parses(spec, vectors):
    # The contract the accepted_inputs field exists to state: a target that
    # passes the vectors accepts every one of these spellings, not just the
    # canonical one. Without it a package could score 101/101 with a parser
    # that handles nothing a Mizo speaker would actually type.
    for vector in vectors:
        n = int(vector["number"])
        for candidate in vector["accepted_inputs"]:
            assert spec.text_to_number(candidate) == n, f"n={n} input={candidate!r}"


def test_canonical_text_is_an_accepted_input(spec, vectors):
    # number_to_text()'s output must always be something text_to_number()
    # accepts. Listing it keeps accepted_inputs self-contained -- a target
    # iterates one field -- and it is the invariant #19 preserved when it
    # settled where number_to_text() emits "leh".
    for vector in vectors:
        assert vector["text"] in vector["accepted_inputs"], vector["number"]


def test_accepted_inputs_are_sorted_and_unique(vectors):
    # The file is compared byte-for-byte in CI to catch a spec edit that
    # wasn't followed by a regenerate, so its ordering has to be stable.
    for vector in vectors:
        inputs = vector["accepted_inputs"]
        assert inputs == sorted(set(inputs)), vector["number"]


@pytest.mark.parametrize(
    "n, feature, expected",
    [
        (11, "case", "SÂWM PAKHAT"),
        (11, "diacritics", "sawm pakhat"),
        (11, "separator", "sâwm-pakhat"),
        (11, "connector", "sâwm leh pakhat"),
        (11, "combined", "SAWM-LEH-PAKHAT"),
        (1, "unit form", "khat"),
        (23, "parse alias", "hnih thum"),
    ],
)
def test_each_parse_feature_is_represented(vectors, n, feature, expected):
    # One entry per parse feature is the whole point of the bounded rule
    # (#12): when a target fails, the variant that failed names the feature
    # that is broken. These spellings are spelled out by hand rather than
    # recomputed from the generator, so a generator change that silently
    # stopped covering a feature fails here instead of passing against its
    # own new output.
    vector = next(v for v in vectors if v["number"] == str(n))
    assert expected in vector["accepted_inputs"], feature


def test_accepted_inputs_do_not_bless_every_connector_gap(vectors):
    # Placement is the last gap only (#10, #12). The engine drops "leh"
    # anywhere by design, but that is engine tolerance, not a target
    # contract: certifying "sawm leh nga leh pariat" would require every
    # future target to accept a string that reads as "10 and 5 and 8"
    # rather than as 58.
    vector = next(v for v in vectors if v["number"] == "58")
    assert "sawm nga leh pariat" in vector["accepted_inputs"]
    assert "sawm leh nga leh pariat" not in vector["accepted_inputs"]


def test_connector_is_not_blessed_where_it_would_be_meaningless(vectors):
    # exact_tens' last gap is its only gap, and it sits before a bound form
    # -- so last-gap-only would certify "sawm leh hnih" for 20. Owner's
    # judgement as a native speaker (#34): that string is meaningless, not a
    # rival reading of 20. Contrast 11 and 58, which end in a standalone
    # form, which is what "leh" takes after it.
    twenty = next(v for v in vectors if v["number"] == "20")
    assert not any("leh" in candidate.lower() for candidate in twenty["accepted_inputs"])
    for n, expected in ((11, "sâwm leh pakhat"), (58, "sawm nga leh pariat")):
        vector = next(v for v in vectors if v["number"] == str(n))
        assert expected in vector["accepted_inputs"]


def test_certified_connectors_are_followed_by_a_top_level_addend(spec, vectors):
    # The rule the test above is a consequence of, stated directly and over
    # every entry rather than the three hand-picked ones: "leh" precedes a
    # top-level addend (#34, generalised by Q-E on #27).
    #
    # An addend is either a standalone unit form ("sâwm leh pakhat") or a
    # scale word heading the next magnitude down ("zâ leh sâwm" = 110,
    # "zâ leh sawm hnih" = 120). What it is never followed by is a *bound*
    # unit form, because that multiplies the scale word before it rather
    # than adding to it -- which is why "sawm leh hnih" (20) and
    # "zâ sawm leh thum" (130) are not Mizo and must not be certified.
    #
    # Until #19 every certified connector happened to be followed by a unit,
    # so this was written as "a standalone unit form". 110 is the first
    # counter-example. The bound-form exclusion is the half that carries the
    # weight and it is unchanged.
    #
    # generate_vectors reads this from parse.connector_precedes -- the spec
    # declares which lexicon fields begin an addend, so the generator states
    # no linguistic fact of its own (#19; #31 is why it must not). This test
    # deliberately rebuilds the addend set from the lexicon instead of reading
    # that declaration, so it cross-checks the spec rather than trusting it:
    # declaring units.bound there would certify "sawm leh hnih", which this
    # test rejects. Being Mizo-specific is fine here; this file is Mizo's.
    addends = {
        spec._normalize_word(entry["standalone"]) for entry in spec.lexicon["units"].values()
    }
    for entry in spec.lexicon["scales"].values():
        addends.update(spec._normalize_word(form) for form in entry.values())
    separators = spec.parse_config["word_separators"]
    connector = spec._normalize_word(spec.parse_config["connectors"][0])
    for vector in vectors:
        for candidate in vector["accepted_inputs"]:
            words = [spec._normalize_word(w) for w in re.split("|".join(separators), candidate)]
            for before, after in zip(words, words[1:]):
                if before == connector:
                    assert after in addends, f"{candidate!r} in n={vector['number']}"


def test_engine_still_tolerates_what_the_vectors_do_not_certify(spec):
    # The other half of both decisions above: the narrower vectors must not
    # be read as the engine having become stricter. These strings still
    # parse -- they are simply not certified, so no target is required to
    # accept them.
    assert spec.text_to_number("sawm leh nga leh pariat") == 58
    assert spec.text_to_number("sawm leh hnih") == 20
    # Both new with #19, and both must stay uncertified. The first is what
    # the generator produced before _connector_slots learned to skip a gap
    # that already holds a connector; the second puts "leh" before a bound
    # digit, which is the 100-199 shape of "sawm leh hnih".
    assert spec.text_to_number("zâ leh leh pariat") == 108
    assert spec.text_to_number("zâ sawm leh thum") == 130


def test_the_string_that_does_mean_ten_and_two_is_certified(spec, vectors):
    # The counterpart to the exact_tens exclusion, and the reason it costs
    # nothing: "sawm leh pahnih" is what a speaker says for "10 and 2" (#34).
    # It parses as 12 -- teens, whose ones digit is standalone -- and is
    # already certified there, so declining to bless "sawm leh hnih" removes
    # no real spelling from the contract. Whether it is one number or two is
    # the inter-number ambiguity #10 put out of scope by design.
    assert spec.text_to_number("sawm leh pahnih") == 12
    twelve = next(v for v in vectors if v["number"] == "12")
    assert "sâwm leh pahnih" in twelve["accepted_inputs"]


def test_no_generated_input_doubles_the_connector(spec):
    # Since #19 the canonical output itself contains "leh", so the generator
    # can add a second one to a gap that already has it -- "zâ leh leh
    # pariat". Nothing downstream would notice: build_vectors parses every
    # candidate back before writing it, and that string parses to 108
    # because _tokenize drops connectors however many there are. Doubled
    # "leh" is not Mizo (Rosie Malsawmtluangi, #19).
    #
    # Generated here rather than read from vectors/mizo.json so that
    # removing the check from _connector_slots fails this immediately,
    # rather than only after someone regenerates.
    connector = spec._normalize_word(spec.parse_config["connectors"][0])
    separators = spec.parse_config["word_separators"]
    for n in generate_vectors.numbers_to_cover(spec):
        for candidate in generate_vectors.accepted_inputs(spec, n):
            words = [spec._normalize_word(w) for w in re.split("|".join(separators), candidate)]
            for before, after in zip(words, words[1:]):
                assert not (before == connector and after == connector), f"{candidate!r} n={n}"


def test_the_connector_dropped_spelling_is_certified(spec, vectors):
    # Q-D on #27 for 108, and the 111-199 bands confirmed by Rosie
    # Malsawmtluangi (#19): where canonical output emits "leh", leaving it
    # out is equally idiomatic. That makes it part of the contract rather
    # than something the engine merely tolerates, so it has to be generated
    # -- it never was before #19, because no canonical string contained a
    # connector to drop.
    for n, dropped in ((108, "zâ pariat"), (128, "zâ sawm hnih pariat")):
        vector = next(v for v in vectors if v["number"] == str(n))
        assert dropped in vector["accepted_inputs"], n


def test_the_two_connector_spelling_is_certified(spec, vectors):
    # From 100 up a number can have two top-level addends after the first,
    # so "leh" can idiomatically appear twice -- confirmed for 128 by the
    # repo owner (#19). Below 100 no number has two, which is why the
    # certified set used to be describable as "the last gap" and why this
    # could not have been tested before now.
    vector = next(v for v in vectors if v["number"] == "128")
    assert "zâ leh sawm hnih leh pariat" in vector["accepted_inputs"]
    # 128 exercises connector_precedes' scales.multiplied entry. 118 is the
    # other half -- a standalone scale form heading an addend -- and it is the
    # only slot scales.standalone enables, every other scale gap already
    # holding the canonical "leh". Without this assertion, dropping that field
    # passes the entire suite and only the CI drift check notices. Form and
    # gap both confirmed by the repo owner in review of #50.
    vector = next(v for v in vectors if v["number"] == "118")
    assert "zâ leh sâwm leh pariat" in vector["accepted_inputs"]


@pytest.mark.parametrize("n", range(0, SUPPORTED_MAX + 1))
def test_canonical_emits_the_connector_exactly_once_above_the_first_scale(spec, n):
    # The output convention (#19): "leh" is emitted once and only once,
    # immediately before the final addend -- the last unit, or the smallest
    # scale word when the last digit is 0. Below 100 it is not emitted at all,
    # though it is still *accepted* ("sâwm leh pakhat" for 11): that asymmetry
    # is deliberate, which is why this counts rather than bans.
    #
    # A property over the range, not a vectors lookup, because this is the
    # invariant #27 must preserve as the range grows -- 10100 is
    # "sîng khat leh zâ": one connector, same position, one magnitude up.
    connector = spec._normalize_word(spec.parse_config["connectors"][0])
    text = spec.number_to_text(n)
    words = [spec._normalize_word(w) for w in text.split()]
    assert words.count(connector) == (1 if n > 100 else 0), text


def test_a_bound_form_is_rejected_as_the_final_addend(spec):
    # Q-E on #27: the trailing digit of "zâ sâwm leh pariat" adds to what
    # precedes it, so it takes the standalone form. "zâ leh riat" uses the
    # bound form and is not a rival reading of 108 -- it is not Mizo.
    # Leniency does not rescue it: that applies only to a phrase which is a
    # single freestanding placeholder, and this one has two.
    with pytest.raises(ValueError):
        spec.text_to_number("zâ leh riat")


def test_stacked_scales_are_not_accepted_below_ten_to_the_fifth(spec):
    # Q-K on #27, as revised: scale words multiply each other from 10^5 up
    # only, so "za sawm hnih" is 120 and not also 10^2 x 20 = 2,000.
    #
    # This cannot currently fail for that reason, and saying so is the point.
    # text_to_number brute-forces range(supports.min, supports.max + 1), so at
    # supports.max = 199 the rival reading 2,000 is never a candidate and no
    # stacking rule could make it one. What the assertions actually pin is
    # narrower: that no *other* number in 0-199 accepts "za sawm hnih", and
    # that 120's canonical spelling is what it should be.
    #
    # Kept rather than deleted, on the #36 precedent -- an invariant can be
    # correct and inert, and the honest move is to document the limit instead
    # of implying coverage. It becomes load-bearing the moment supports.max
    # passes 2,000, which is when #27's stacking rule arrives.
    assert spec.text_to_number("za sawm hnih") == 120
    assert spec.number_to_text(120) == "zâ leh sawm hnih"


def test_exhaustive_variants_all_parse(spec):
    # The bounded vectors assume parse features compose: each is one stage
    # of a pipeline, so covering them separately covers them together. That
    # assumption is what makes one representative per feature sufficient,
    # and this is where it is actually checked -- the full cross product of
    # every template, every respelling, and the connector in every gap.
    #
    # It lives here rather than in vectors/mizo.json on purpose. A target
    # package cannot import reference/, so this proves the property for the
    # oracle; what protects a target is the composition assumption plus the
    # fact that #20's package is compiled from the same spec.
    checked = 0
    for n in generate_vectors.numbers_to_cover(spec):
        for candidate in generate_vectors.accepted_inputs(spec, n, exhaustive=True):
            assert spec.text_to_number(candidate) == n, f"n={n} input={candidate!r}"
            checked += 1
    assert checked > 1000, checked


@pytest.mark.parametrize("n", range(0, SUPPORTED_MAX + 1))
def test_round_trip_number_text_number(spec, n):
    # number -> text -> number must return the original value.
    assert spec.text_to_number(spec.number_to_text(n)) == n


@pytest.mark.parametrize("n", range(0, SUPPORTED_MAX + 1))
def test_round_trip_text_number_text(spec, n):
    # text -> number -> text must be stable for canonical text.
    text = spec.number_to_text(n)
    assert spec.number_to_text(spec.text_to_number(text)) == text


def test_connector_word_is_ignored(spec):
    # "leh" is a connector (parse.connectors in mizo.yaml) and must not
    # affect parsing even though number_to_text() never produces it.
    assert spec.text_to_number("sawm hnih leh pahnih") == 22
    assert spec.text_to_number("sawm leh pahnih") == spec.text_to_number("sawm pahnih")


def test_text_to_number_is_case_insensitive(spec):
    assert spec.text_to_number("SAWM HNIH") == 20


@pytest.mark.parametrize(
    "text",
    [
        " sawm nga pariat",       # leading
        "sawm nga pariat ",       # trailing
        "sawm  nga pariat",       # repeated
        " sawm  nga   pariat ",   # all three at once
        "sawm-nga pariat",        # a mix of the two separators
        "sawm--nga-pariat",       # repeated, on the other separator
    ],
)
def test_stray_and_repeated_separators_are_ignored(spec, text):
    # Splitting on word_separators leaves an empty string wherever two
    # separators meet or one sits at either end; _tokenize drops those.
    # No vector can reach this (#40): generate_vectors.py builds every
    # accepted_input by joining words, so all of them are well-formed by
    # construction.
    #
    # It is real input rather than a curiosity. mizo.yaml's header names a
    # post-ASR pipeline as the expected caller, and that is exactly where
    # ragged spacing comes from.
    assert spec.text_to_number(text) == 58


@pytest.mark.parametrize("text", ["", " ", "   ", "-", " - "])
def test_text_that_is_only_separators_raises(spec, text):
    # The other half of the same code path: dropping the empty strings
    # leaves no tokens at all, and no rule matches nothing. Worth pinning
    # so leniency about stray separators never turns into accepting a
    # phrase that names no number.
    with pytest.raises(ValueError):
        spec.text_to_number(text)


@pytest.mark.parametrize(
    "n, expected",
    [
        (10, "sâwm"),          # not multiplied -- circumflex kept
        (11, "sâwm pakhat"),   # additive digit (10+1), still not multiplied
        (20, "sawm hnih"),     # multiplying digit (10x2) -- circumflex removed
        (30, "sawm thum"),
        (100, "zâ"),           # not multiplied
    ],
)
def test_scale_word_diacritic_alternates_with_multiplication(spec, n, expected):
    # The circumflex on a scale word is part of the grammar, not just
    # decoration. It shows the word is not multiplied (#15). We test this
    # directly instead of relying only on vectors/mizo.json, because those
    # vectors are generated by the same engine and could hide the same bug.
    assert spec.number_to_text(n) == expected


@pytest.mark.parametrize("text, expected", [("sawm", 10), ("sawm pakhat", 11), ("za", 100)])
def test_undiacriticked_input_parses(spec, text, expected):
    # parse.strip_diacritics (#15): most people type on an ASCII keyboard,
    # so input written without the circumflex must still work.
    assert spec.text_to_number(text) == expected


@pytest.mark.parametrize("text, expected", [("sâwm", 10), ("sâwm pakhat", 11), ("zâ", 100)])
def test_diacriticked_input_still_parses(spec, text, expected):
    # The normal spelling must still work. Removing diacritics is an extra
    # convenience, not a replacement for exact matching.
    assert spec.text_to_number(text) == expected


def test_strip_diacritics_and_case_insensitivity_compose(spec):
    assert spec.text_to_number("SAWM PAKHAT") == 11


def test_strip_diacritics_is_what_accepts_undiacriticked_input():
    # Test the mechanism with simple data. If the flag is off, the plain
    # spelling must not match. Otherwise, the tests above could still pass
    # for another reason and the flag could be removed without anyone
    # noticing.
    data = {
        "meta": {"supports": {"min": 10, "max": 10}},
        "lexicon": {"scales": {10: {"standalone": "sâwm", "multiplied": "sawm"}}},
        "grammar": {
            "rules": [{"name": "ten", "range": [10, 10], "output": "{scales[10].standalone}"}]
        },
        "parse": {},
    }
    strict = Spec(data)
    assert strict.text_to_number("sâwm") == 10
    with pytest.raises(ValueError):
        strict.text_to_number("sawm")

    lenient = Spec({**data, "parse": {"strip_diacritics": True}})
    assert lenient.text_to_number("sawm") == 10
    assert lenient.text_to_number("sâwm") == 10


def test_connectors_are_normalised_before_being_dropped():
    # A connector written with a diacritic must still be dropped when the
    # input is typed without one. _tokenize normalises the connector list
    # with the same function it uses on the input, so the two meet in the
    # middle. If it normalised only the input, the connector would stop
    # matching and be left behind as a token no rule can explain.
    data = {
        "meta": {"supports": {"min": 5, "max": 5}},
        "lexicon": {"units": {5: {"standalone": "canonical_five", "bound": "canonical_five"}}},
        "grammar": {
            "rules": [{"name": "units", "range": [0, 9], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {"strip_diacritics": True, "connectors": ["lêh"]},
    }
    spec = Spec(data)
    assert spec.text_to_number("canonical_five lêh") == 5
    assert spec.text_to_number("canonical_five leh") == 5


def test_aliases_are_normalised_on_both_sides():
    # Same idea for aliases, which substitute instead of dropping. A
    # diacritic can sit on the variant, on the canonical word it maps to, or
    # on both. The value side is the easy one to miss: normalising only the
    # key would resolve the alias to a spelling the rules never match, so the
    # substitution would succeed and the parse would still fail.
    data = {
        "meta": {"supports": {"min": 5, "max": 5}},
        "lexicon": {"units": {5: {"standalone": "canônical_five", "bound": "canônical_five"}}},
        "grammar": {
            "rules": [{"name": "units", "range": [0, 9], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {"strip_diacritics": True, "aliases": {"âlt_five": "canônical_five"}},
    }
    spec = Spec(data)
    assert spec.text_to_number("âlt_five") == 5
    assert spec.text_to_number("alt_five") == 5
    assert spec.text_to_number("canonical_five") == 5


def test_unparseable_text_raises(spec):
    with pytest.raises(ValueError):
        spec.text_to_number("not mizo words")


@pytest.mark.parametrize("n", range(0, 10))
def test_freestanding_digit_accepts_bound_form(spec, n):
    # A lone digit may be spoken in bound form too, e.g. "khat" as well as
    # the canonical standalone "pakhat" for 1 -- parse.accepted_forms in
    # mizo.yaml lists `bound` as an extra form, the standalone form being
    # accepted anyway as the field the template names. Both apply only to a
    # freestanding digit; multi-word rules must keep matching their named
    # field exactly (see test_bound_form_is_not_accepted_mid_phrase).
    bound_word = spec.lexicon["units"][n]["bound"]
    assert spec.text_to_number(bound_word) == n


def test_bound_form_is_not_accepted_mid_phrase(spec):
    # "sawm hnih" must mean 20 (exact_tens' canonical bound tens-digit slot),
    # not also match teens' ones-digit slot via bound-form leniency -- that
    # would make 12 and 20 ambiguous for the same input.
    assert spec.text_to_number("sawm hnih") == 20


def test_leniency_follows_the_table_the_spec_names(spec):
    # #31: the engine used to check `table != "units"`, so a language whose
    # digits lived in a differently named table lost leniency no matter what
    # it declared. Rename the table throughout and behaviour must follow the
    # spec, not the name.
    data = copy.deepcopy(spec._data)
    data["lexicon"]["digits"] = data["lexicon"].pop("units")
    for rule in data["grammar"]["rules"]:
        rule["output"] = rule["output"].replace("{units[", "{digits[")
        if "parse_aliases" in rule:
            rule["parse_aliases"] = [
                template.replace("{units[", "{digits[")
                for template in rule["parse_aliases"]
            ]
    data["parse"]["accepted_forms"] = {"digits": ["standalone", "bound"]}
    renamed = Spec(data)

    assert renamed.text_to_number("pakhat") == 1
    assert renamed.text_to_number("khat") == 1


def test_a_spec_that_declares_nothing_gets_exact_matching(spec):
    # The English case (#31), reproduced against Mizo's data: with no
    # accepted_forms at all, only the field each template names matches.
    data = copy.deepcopy(spec._data)
    del data["parse"]["accepted_forms"]
    strict = Spec(data)

    assert strict.text_to_number("pakhat") == 1
    with pytest.raises(ValueError):
        strict.text_to_number("khat")


def test_the_field_a_template_names_always_matches(spec):
    # A spec cannot break its own canonical spelling by leaving that field
    # out of the list: number_to_text() emits the field the template names,
    # so it has to parse back. units names `standalone` and the list mentions
    # only `bound`, and the round-trip still holds. mizo.yaml is written that
    # way, so the vectors cover this too -- deliberately, since a renderer
    # that reads only the list would otherwise pass conformance while
    # dropping the rule. This states it directly rather than by side effect;
    # it is set explicitly so the test keeps its meaning if the spec changes.
    data = copy.deepcopy(spec._data)
    data["parse"]["accepted_forms"] = {"units": ["bound"]}
    partial = Spec(data)

    for n in range(0, 10):
        assert partial.text_to_number(partial.number_to_text(n)) == n


def test_aliases_resolve_to_canonical_word_before_matching():
    # parse.aliases lets an alternate spelling resolve to the canonical
    # lexicon word before rule matching. Same mechanism as parse.connectors,
    # just substituting instead of dropping. mizo.yaml's alias list is empty
    # and settled -- a native speaker confirmed Mizo 0-199 has no
    # non-diacritic spelling variants -- so this uses synthetic placeholder
    # words rather than asserting real Mizo spellings.
    data = {
        "meta": {"supports": {"min": 5, "max": 5}},
        "lexicon": {"units": {5: {"standalone": "canonical_five", "bound": "canonical_five"}}},
        "grammar": {
            "rules": [{"name": "units", "range": [0, 9], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {"aliases": {"alt_five": "canonical_five"}},
    }
    spec = Spec(data)
    assert spec.text_to_number("alt_five") == 5
    assert spec.text_to_number("canonical_five") == 5


@pytest.mark.parametrize(
    "shorthand, expected",
    [("hnih thum", 23), ("ruk ruk", 66), ("ruk riat", 68)],
)
def test_compound_tens_shorthand_parses(spec, shorthand, expected):
    # compound_tens' parse_aliases in mizo.yaml accept a shorthand that drops
    # the scale word and uses the bound form of both digits -- e.g. "hnih
    # thum" for 23, alongside the canonical "sawm hnih pathum".
    assert spec.text_to_number(shorthand) == expected


def test_compound_tens_shorthand_does_not_affect_number_to_text(spec):
    # parse_aliases are accepted on the way in only; number_to_text() must
    # keep producing the canonical form regardless.
    assert spec.number_to_text(23) == "sawm hnih pathum"


def test_parse_aliases_are_tried_in_addition_to_canonical_output():
    # Mechanism test with synthetic data: a rule's parse_aliases template is
    # matched alongside (not instead of) its canonical output.
    data = {
        "meta": {"supports": {"min": 0, "max": 0}},
        "lexicon": {
            "units": {0: {"standalone": "canonical_zero", "bound": "shorthand_zero"}}
        },
        "grammar": {
            "rules": [{
                "name": "units",
                "range": [0, 0],
                "output": "{units[ones_digit].standalone}",
                "parse_aliases": ["{units[ones_digit].bound}"],
            }]
        },
        "parse": {},
    }
    spec = Spec(data)
    assert spec.text_to_number("canonical_zero") == 0
    assert spec.text_to_number("shorthand_zero") == 0


def test_parse_alias_collision_raises_ambiguous():
    # If a parse_aliases template happens to match another number's
    # canonical spelling, that's a real ambiguity and must be a loud error,
    # same as a canonical-vs-canonical collision.
    data = {
        "meta": {"supports": {"min": 0, "max": 1}},
        "lexicon": {
            "units": {
                0: {"standalone": "zero_word", "bound": "shared_word"},
                1: {"standalone": "shared_word", "bound": "shared_word"},
            }
        },
        "grammar": {
            "rules": [{
                "name": "units",
                "range": [0, 1],
                "output": "{units[ones_digit].standalone}",
                "parse_aliases": ["{units[ones_digit].bound}"],
            }]
        },
        "parse": {},
    }
    spec = Spec(data)
    with pytest.raises(ValueError, match="ambiguous"):
        spec.text_to_number("shared_word")


def test_ambiguous_match_raises():
    # If a future grammar ever let two different numbers accept the same
    # spelling, text_to_number() must raise rather than silently returning
    # whichever number happened to come first in the range -- this is the
    # oracle, so an ambiguous spelling is a data bug to surface loudly, not
    # a thing to guess through. Uses synthetic data since mizo.yaml has no
    # such collision today (verified across the full 0-199 range).
    data = {
        "meta": {"supports": {"min": 0, "max": 1}},
        "lexicon": {
            "units": {
                0: {"standalone": "same_word", "bound": "same_word"},
                1: {"standalone": "same_word", "bound": "same_word"},
            }
        },
        "grammar": {
            "rules": [{"name": "units", "range": [0, 1], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {},
    }
    spec = Spec(data)
    with pytest.raises(ValueError, match="ambiguous"):
        spec.text_to_number("same_word")
