"""Tests for the reference engine (engine.py). Two independent artifacts are
checked against, on purpose, because they prove different things:

- mizo.yaml's examples: block -- 12 pairs a native speaker wrote by hand.
  Independent ground truth: catches a numeral that's simply wrong.
- vectors/mizo.json -- generated from the engine by generate_vectors.py and
  checked into git; it is NOT regenerated by these tests. Catches drift: a
  spec edit whose output changed without a regenerate. It canNOT catch a
  wrong-but-dutifully-regenerated numeral, since it's generated from the
  same engine it's tested against -- that's what the examples: test is for.
  Each entry also carries accepted_inputs: representative spellings
  text_to_number() must accept, one per applicable parse feature (#12). That
  is the half of the contract `text` alone can't state -- a target package
  can match every canonical string and still reject everything a Mizo
  speaker types. See generate_vectors.accepted_inputs() for the rule.

mizo.yaml's core numeral data has been verified by a native Mizo speaker
(see meta.sources). The "leh" connector (parse.connectors) is a separate,
deliberate exception -- not unverified, but a documented team decision to
leave it unresolved (see mizo.yaml's header and its `# Decision (#10)` tag).
Nothing in mizo.yaml is marked TODO(verify) as of #15: parse.aliases was the
last one, and its diacritic part is now handled by parse.strip_diacritics.
These tests check that the engine correctly follows the grammar as written,
not whether the grammar itself is linguistically correct.
"""

import json
import re
from pathlib import Path

import pytest

import generate_vectors
from engine import Spec, load

MIZO_SPEC_PATH = Path(__file__).resolve().parent.parent / "languages" / "mizo.yaml"
VECTORS_PATH = Path(__file__).resolve().parent.parent / "vectors" / "mizo.json"


@pytest.fixture(scope="module")
def spec():
    return load(MIZO_SPEC_PATH)


@pytest.fixture(scope="module")
def vectors():
    with open(VECTORS_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def test_examples_match(spec):
    # mizo.yaml's examples: are hand-written by a native speaker -- the
    # independent anchor. vectors/mizo.json is generated from the engine,
    # so it can only catch drift, never a wrong-but-regenerated numeral.
    for example in spec.examples:
        assert spec.number_to_text(example["number"]) == example["text"], f"n={example['number']}"


def test_vectors_match_number_to_text(spec, vectors):
    for vector in vectors:
        n = int(vector["number"])
        assert spec.number_to_text(n) == vector["text"], f"n={n}"


def test_vector_numbers_are_strings(vectors):
    # #12: `number` is deliberately a string, so that a JS target reading
    # this file cannot silently lose precision above 2^53 - 1 once the range
    # grows (#27 puts Mizo's ceiling at 10^18 - 1). Nothing in the current
    # 0-100 range needs it; the format does. Asserted so that a future
    # regenerate cannot quietly drop back to a JSON number.
    for vector in vectors:
        assert isinstance(vector["number"], str), vector


@pytest.mark.parametrize("n", range(0, 101))
def test_every_number_in_range_has_a_matching_rule(spec, n):
    # Every number in the supported range must match some grammar rule --
    # this catches gaps/overlaps in rule ranges even for numbers we don't
    # have a hand-written example for.
    spec.number_to_text(n)


def test_out_of_range_raises(spec):
    with pytest.raises(ValueError):
        spec.number_to_text(101)
    with pytest.raises(ValueError):
        spec.number_to_text(-1)


def test_vectors_parse_back(spec, vectors):
    for vector in vectors:
        assert spec.text_to_number(vector["text"]) == int(vector["number"])


def test_every_accepted_input_parses(spec, vectors):
    # The contract the accepted_inputs field exists to state: a target that
    # passes the vectors accepts every one of these spellings, not just the
    # canonical one. Without it a package could score 101/101 with a parser
    # that handles nothing a Mizo speaker would actually type.
    for vector in vectors:
        n = int(vector["number"])
        for candidate in vector["accepted_inputs"]:
            assert spec.text_to_number(candidate) == n, f"n={n} input={candidate!r}"


def test_canonical_text_is_an_accepted_input(spec, vectors):
    # number_to_text()'s output must always be something text_to_number()
    # accepts. Listing it keeps accepted_inputs self-contained -- a target
    # iterates one field -- and it is the invariant #19 has to preserve when
    # it decides where number_to_text() emits "leh".
    for vector in vectors:
        assert vector["text"] in vector["accepted_inputs"], vector["number"]


def test_accepted_inputs_are_sorted_and_unique(vectors):
    # The file is compared byte-for-byte in CI to catch a spec edit that
    # wasn't followed by a regenerate, so its ordering has to be stable.
    for vector in vectors:
        inputs = vector["accepted_inputs"]
        assert inputs == sorted(set(inputs)), vector["number"]


@pytest.mark.parametrize(
    "n, feature, expected",
    [
        (11, "case", "SÂWM PAKHAT"),
        (11, "diacritics", "sawm pakhat"),
        (11, "separator", "sâwm-pakhat"),
        (11, "connector", "sâwm leh pakhat"),
        (11, "combined", "SAWM-LEH-PAKHAT"),
        (1, "unit form", "khat"),
        (23, "parse alias", "hnih thum"),
    ],
)
def test_each_parse_feature_is_represented(vectors, n, feature, expected):
    # One entry per parse feature is the whole point of the bounded rule
    # (#12): when a target fails, the variant that failed names the feature
    # that is broken. These spellings are spelled out by hand rather than
    # recomputed from the generator, so a generator change that silently
    # stopped covering a feature fails here instead of passing against its
    # own new output.
    vector = next(v for v in vectors if v["number"] == str(n))
    assert expected in vector["accepted_inputs"], feature


def test_accepted_inputs_do_not_bless_every_connector_gap(vectors):
    # Placement is the last gap only (#10, #12). The engine drops "leh"
    # anywhere by design, but that is engine tolerance, not a target
    # contract: certifying "sawm leh nga leh pariat" would require every
    # future target to accept a string that reads as "10 and 5 and 8"
    # rather than as 58.
    vector = next(v for v in vectors if v["number"] == "58")
    assert "sawm nga leh pariat" in vector["accepted_inputs"]
    assert "sawm leh nga leh pariat" not in vector["accepted_inputs"]


def test_connector_is_not_blessed_where_it_would_be_meaningless(vectors):
    # exact_tens' last gap is its only gap, and it sits before a bound form
    # -- so last-gap-only would certify "sawm leh hnih" for 20. Owner's
    # judgement as a native speaker (#34): that string is meaningless, not a
    # rival reading of 20. Contrast 11 and 58, which end in a standalone
    # form, which is what "leh" takes after it.
    twenty = next(v for v in vectors if v["number"] == "20")
    assert not any("leh" in candidate.lower() for candidate in twenty["accepted_inputs"])
    for n, expected in ((11, "sâwm leh pakhat"), (58, "sawm nga leh pariat")):
        vector = next(v for v in vectors if v["number"] == str(n))
        assert expected in vector["accepted_inputs"]


def test_certified_connectors_are_followed_by_a_standalone_form(spec, vectors):
    # The rule the test above is a consequence of, stated directly and over
    # every entry rather than the three hand-picked ones: "leh" takes a
    # standalone unit form after it (#34).
    #
    # generate_vectors detects this positionally -- does the last placeholder
    # address the ones digit? -- because keying off the field name
    # "standalone" would hardcode Mizo's vocabulary into language-agnostic
    # code (#31). That makes it a proxy, and this is the test that would
    # notice if the proxy and the rule ever came apart. Being Mizo-specific
    # is fine here; this file is Mizo's.
    standalone = {
        spec._normalize_word(entry["standalone"]) for entry in spec.lexicon["units"].values()
    }
    separators = spec.parse_config["word_separators"]
    connector = spec._normalize_word(spec.parse_config["connectors"][0])
    for vector in vectors:
        for candidate in vector["accepted_inputs"]:
            words = [spec._normalize_word(w) for w in re.split("|".join(separators), candidate)]
            for before, after in zip(words, words[1:]):
                if before == connector:
                    assert after in standalone, f"{candidate!r} in n={vector['number']}"


def test_engine_still_tolerates_what_the_vectors_do_not_certify(spec):
    # The other half of both decisions above: the narrower vectors must not
    # be read as the engine having become stricter. These strings still
    # parse -- they are simply not certified, so no target is required to
    # accept them.
    assert spec.text_to_number("sawm leh nga leh pariat") == 58
    assert spec.text_to_number("sawm leh hnih") == 20


def test_the_string_that_does_mean_ten_and_two_is_certified(spec, vectors):
    # The counterpart to the exact_tens exclusion, and the reason it costs
    # nothing: "sawm leh pahnih" is what a speaker says for "10 and 2" (#34).
    # It parses as 12 -- teens, whose ones digit is standalone -- and is
    # already certified there, so declining to bless "sawm leh hnih" removes
    # no real spelling from the contract. Whether it is one number or two is
    # the inter-number ambiguity #10 put out of scope by design.
    assert spec.text_to_number("sawm leh pahnih") == 12
    twelve = next(v for v in vectors if v["number"] == "12")
    assert "sâwm leh pahnih" in twelve["accepted_inputs"]


def test_exhaustive_variants_all_parse(spec):
    # The bounded vectors assume parse features compose: each is one stage
    # of a pipeline, so covering them separately covers them together. That
    # assumption is what makes one representative per feature sufficient,
    # and this is where it is actually checked -- the full cross product of
    # every template, every respelling, and the connector in every gap.
    #
    # It lives here rather than in vectors/mizo.json on purpose. A target
    # package cannot import reference/, so this proves the property for the
    # oracle; what protects a target is the composition assumption plus the
    # fact that #20's package is compiled from the same spec.
    checked = 0
    for n in generate_vectors.numbers_to_cover(spec):
        for candidate in generate_vectors.accepted_inputs(spec, n, exhaustive=True):
            assert spec.text_to_number(candidate) == n, f"n={n} input={candidate!r}"
            checked += 1
    assert checked > 1000, checked


@pytest.mark.parametrize("n", range(0, 101))
def test_round_trip_number_text_number(spec, n):
    # number -> text -> number must return the original value.
    assert spec.text_to_number(spec.number_to_text(n)) == n


@pytest.mark.parametrize("n", range(0, 101))
def test_round_trip_text_number_text(spec, n):
    # text -> number -> text must be stable for canonical text.
    text = spec.number_to_text(n)
    assert spec.number_to_text(spec.text_to_number(text)) == text


def test_connector_word_is_ignored(spec):
    # "leh" is a connector (parse.connectors in mizo.yaml) and must not
    # affect parsing even though number_to_text() never produces it.
    assert spec.text_to_number("sawm hnih leh pahnih") == 22
    assert spec.text_to_number("sawm leh pahnih") == spec.text_to_number("sawm pahnih")


def test_text_to_number_is_case_insensitive(spec):
    assert spec.text_to_number("SAWM HNIH") == 20


@pytest.mark.parametrize(
    "n, expected",
    [
        (10, "sâwm"),          # not multiplied -- circumflex kept
        (11, "sâwm pakhat"),   # additive digit (10+1), still not multiplied
        (20, "sawm hnih"),     # multiplying digit (10x2) -- circumflex removed
        (30, "sawm thum"),
        (100, "zâ"),           # not multiplied
    ],
)
def test_scale_word_diacritic_alternates_with_multiplication(spec, n, expected):
    # The circumflex on a scale word is part of the grammar, not just
    # decoration. It shows the word is not multiplied (#15). We test this
    # directly instead of relying only on vectors/mizo.json, because those
    # vectors are generated by the same engine and could hide the same bug.
    assert spec.number_to_text(n) == expected


@pytest.mark.parametrize("text, expected", [("sawm", 10), ("sawm pakhat", 11), ("za", 100)])
def test_undiacriticked_input_parses(spec, text, expected):
    # parse.strip_diacritics (#15): most people type on an ASCII keyboard,
    # so input written without the circumflex must still work.
    assert spec.text_to_number(text) == expected


@pytest.mark.parametrize("text, expected", [("sâwm", 10), ("sâwm pakhat", 11), ("zâ", 100)])
def test_diacriticked_input_still_parses(spec, text, expected):
    # The normal spelling must still work. Removing diacritics is an extra
    # convenience, not a replacement for exact matching.
    assert spec.text_to_number(text) == expected


def test_strip_diacritics_and_case_insensitivity_compose(spec):
    assert spec.text_to_number("SAWM PAKHAT") == 11


def test_strip_diacritics_is_what_accepts_undiacriticked_input():
    # Test the mechanism with simple data. If the flag is off, the plain
    # spelling must not match. Otherwise, the tests above could still pass
    # for another reason and the flag could be removed without anyone
    # noticing.
    data = {
        "meta": {"supports": {"min": 10, "max": 10}},
        "lexicon": {"scales": {10: {"standalone": "sâwm", "multiplied": "sawm"}}},
        "grammar": {
            "rules": [{"name": "ten", "range": [10, 10], "output": "{scales[10].standalone}"}]
        },
        "parse": {},
    }
    strict = Spec(data)
    assert strict.text_to_number("sâwm") == 10
    with pytest.raises(ValueError):
        strict.text_to_number("sawm")

    lenient = Spec({**data, "parse": {"strip_diacritics": True}})
    assert lenient.text_to_number("sawm") == 10
    assert lenient.text_to_number("sâwm") == 10


def test_connectors_are_normalised_before_being_dropped():
    # A connector written with a diacritic must still be dropped when the
    # input is typed without one. _tokenize normalises the connector list
    # with the same function it uses on the input, so the two meet in the
    # middle. If it normalised only the input, the connector would stop
    # matching and be left behind as a token no rule can explain.
    data = {
        "meta": {"supports": {"min": 5, "max": 5}},
        "lexicon": {"units": {5: {"standalone": "canonical_five", "bound": "canonical_five"}}},
        "grammar": {
            "rules": [{"name": "units", "range": [0, 9], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {"strip_diacritics": True, "connectors": ["lêh"]},
    }
    spec = Spec(data)
    assert spec.text_to_number("canonical_five lêh") == 5
    assert spec.text_to_number("canonical_five leh") == 5


def test_aliases_are_normalised_on_both_sides():
    # Same idea for aliases, which substitute instead of dropping. A
    # diacritic can sit on the variant, on the canonical word it maps to, or
    # on both. The value side is the easy one to miss: normalising only the
    # key would resolve the alias to a spelling the rules never match, so the
    # substitution would succeed and the parse would still fail.
    data = {
        "meta": {"supports": {"min": 5, "max": 5}},
        "lexicon": {"units": {5: {"standalone": "canônical_five", "bound": "canônical_five"}}},
        "grammar": {
            "rules": [{"name": "units", "range": [0, 9], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {"strip_diacritics": True, "aliases": {"âlt_five": "canônical_five"}},
    }
    spec = Spec(data)
    assert spec.text_to_number("âlt_five") == 5
    assert spec.text_to_number("alt_five") == 5
    assert spec.text_to_number("canonical_five") == 5


def test_unparseable_text_raises(spec):
    with pytest.raises(ValueError):
        spec.text_to_number("not mizo words")


@pytest.mark.parametrize("n", range(0, 10))
def test_freestanding_digit_accepts_bound_form(spec, n):
    # A lone digit may be spoken in bound form too, e.g. "khat" as well as
    # the canonical standalone "pakhat" for 1 -- parse.accepted_forms in
    # mizo.yaml declares both acceptable, but only for a freestanding digit;
    # multi-word rules must keep matching their named field exactly (see
    # test_bound_form_is_not_accepted_mid_phrase).
    bound_word = spec.lexicon["units"][n]["bound"]
    assert spec.text_to_number(bound_word) == n


def test_bound_form_is_not_accepted_mid_phrase(spec):
    # "sawm hnih" must mean 20 (exact_tens' canonical bound tens-digit slot),
    # not also match teens' ones-digit slot via bound-form leniency -- that
    # would make 12 and 20 ambiguous for the same input.
    assert spec.text_to_number("sawm hnih") == 20


def test_aliases_resolve_to_canonical_word_before_matching():
    # parse.aliases lets an alternate spelling resolve to the canonical
    # lexicon word before rule matching. Same mechanism as parse.connectors,
    # just substituting instead of dropping. mizo.yaml's alias list is empty
    # and settled -- a native speaker confirmed Mizo 0-100 has no
    # non-diacritic spelling variants -- so this uses synthetic placeholder
    # words rather than asserting real Mizo spellings.
    data = {
        "meta": {"supports": {"min": 5, "max": 5}},
        "lexicon": {"units": {5: {"standalone": "canonical_five", "bound": "canonical_five"}}},
        "grammar": {
            "rules": [{"name": "units", "range": [0, 9], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {"aliases": {"alt_five": "canonical_five"}},
    }
    spec = Spec(data)
    assert spec.text_to_number("alt_five") == 5
    assert spec.text_to_number("canonical_five") == 5


@pytest.mark.parametrize(
    "shorthand, expected",
    [("hnih thum", 23), ("ruk ruk", 66), ("ruk riat", 68)],
)
def test_compound_tens_shorthand_parses(spec, shorthand, expected):
    # compound_tens' parse_aliases in mizo.yaml accept a shorthand that drops
    # the scale word and uses the bound form of both digits -- e.g. "hnih
    # thum" for 23, alongside the canonical "sawm hnih pathum".
    assert spec.text_to_number(shorthand) == expected


def test_compound_tens_shorthand_does_not_affect_number_to_text(spec):
    # parse_aliases are accepted on the way in only; number_to_text() must
    # keep producing the canonical form regardless.
    assert spec.number_to_text(23) == "sawm hnih pathum"


def test_parse_aliases_are_tried_in_addition_to_canonical_output():
    # Mechanism test with synthetic data: a rule's parse_aliases template is
    # matched alongside (not instead of) its canonical output.
    data = {
        "meta": {"supports": {"min": 0, "max": 0}},
        "lexicon": {
            "units": {0: {"standalone": "canonical_zero", "bound": "shorthand_zero"}}
        },
        "grammar": {
            "rules": [{
                "name": "units",
                "range": [0, 0],
                "output": "{units[ones_digit].standalone}",
                "parse_aliases": ["{units[ones_digit].bound}"],
            }]
        },
        "parse": {},
    }
    spec = Spec(data)
    assert spec.text_to_number("canonical_zero") == 0
    assert spec.text_to_number("shorthand_zero") == 0


def test_parse_alias_collision_raises_ambiguous():
    # If a parse_aliases template happens to match another number's
    # canonical spelling, that's a real ambiguity and must be a loud error,
    # same as a canonical-vs-canonical collision.
    data = {
        "meta": {"supports": {"min": 0, "max": 1}},
        "lexicon": {
            "units": {
                0: {"standalone": "zero_word", "bound": "shared_word"},
                1: {"standalone": "shared_word", "bound": "shared_word"},
            }
        },
        "grammar": {
            "rules": [{
                "name": "units",
                "range": [0, 1],
                "output": "{units[ones_digit].standalone}",
                "parse_aliases": ["{units[ones_digit].bound}"],
            }]
        },
        "parse": {},
    }
    spec = Spec(data)
    with pytest.raises(ValueError, match="ambiguous"):
        spec.text_to_number("shared_word")


def test_ambiguous_match_raises():
    # If a future grammar ever let two different numbers accept the same
    # spelling, text_to_number() must raise rather than silently returning
    # whichever number happened to come first in the range -- this is the
    # oracle, so an ambiguous spelling is a data bug to surface loudly, not
    # a thing to guess through. Uses synthetic data since mizo.yaml has no
    # such collision today (verified across the full 0-100 range).
    data = {
        "meta": {"supports": {"min": 0, "max": 1}},
        "lexicon": {
            "units": {
                0: {"standalone": "same_word", "bound": "same_word"},
                1: {"standalone": "same_word", "bound": "same_word"},
            }
        },
        "grammar": {
            "rules": [{"name": "units", "range": [0, 1], "output": "{units[ones_digit].standalone}"}]
        },
        "parse": {},
    }
    spec = Spec(data)
    with pytest.raises(ValueError, match="ambiguous"):
        spec.text_to_number("same_word")
